package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "asistencia")
public class Asistencia implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long asisId;
	private DetalleHorario detalleHorario;
	private Empleado empleado;
	private Date fechaHoraHorario;
	private Date fechaHoraTimbre;
	
	private Date fechaHorario;
	private Date HoraHorario;
	
	private Date fechaTimbre;
	private Date HoraTimbre;
	
	private String entradaSalida;
	private String codigoEmpleado;
	private Integer asisOrden;
	private int asisMaxMinuto;
	private String estado;
	private Set<AsistenciaHoraExtra> asistenciaHoraExtras = new HashSet<AsistenciaHoraExtra>(
			0);
	
	private Date fechaDesde;
	private Date fechaHasta;
	private Long dehoIdNuevo;
	private Long modificado;
	private String observacion;
	
	public Asistencia() {
	}

	public Asistencia(DetalleHorario detalleHorario, Empleado empleado,
			Date fechaHoraHorario, String entradaSalida, String codigoEmpleado,
			Integer asisOrden, int asisMaxMinuto, String estado, Long dehoIdNuevo) {
		this.detalleHorario = detalleHorario;
		this.empleado = empleado;
		this.fechaHoraHorario = fechaHoraHorario;
		this.entradaSalida = entradaSalida;
		this.codigoEmpleado = codigoEmpleado;
		this.asisOrden = asisOrden;
		this.asisMaxMinuto = asisMaxMinuto;
		this.estado = estado;
		this.dehoIdNuevo=dehoIdNuevo;
	}
	public Asistencia(DetalleHorario detalleHorario, Empleado empleado,
			Date fechaHoraHorario, Date fechaHoraTimbre, String entradaSalida,
			String codigoEmpleado, Integer asisOrden, int asisMaxMinuto,
			String estado, Set<AsistenciaHoraExtra> asistenciaHoraExtras, Long dehoIdNuevo,
			String obserbacion) {
		this.detalleHorario = detalleHorario;
		this.empleado = empleado;
		this.fechaHoraHorario = fechaHoraHorario;
		this.fechaHoraTimbre = fechaHoraTimbre;
		this.entradaSalida = entradaSalida;
		this.codigoEmpleado = codigoEmpleado;
		this.asisOrden = asisOrden;
		this.asisMaxMinuto = asisMaxMinuto;
		this.estado = estado;
		this.asistenciaHoraExtras = asistenciaHoraExtras;
		this.dehoIdNuevo = dehoIdNuevo;
		this.observacion = obserbacion;
	}

	@Id
	@TableGenerator(name = "IDASISTENCIA", table = "contadores", pkColumnName = "ID", pkColumnValue = "20", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDASISTENCIA")
	@Column(name = "ASIS_ID", unique = true, nullable = false)
	public Long getAsisId() {
		return this.asisId;
	}

	public void setAsisId(Long asisId) {
		this.asisId = asisId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEHO_ID", nullable = false)
	@NotNull
	public DetalleHorario getDetalleHorario() {
		if (detalleHorario==null){
			detalleHorario=new DetalleHorario();
			
		}
		return this.detalleHorario;
	}

	public void setDetalleHorario(DetalleHorario detalleHorario) {
		this.detalleHorario = detalleHorario;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleado() {
		if(empleado == null){
			empleado = new Empleado();
		}
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_HORA_HORARIO", nullable = false, length = 19)
	@NotNull
	public Date getFechaHoraHorario() {
		return this.fechaHoraHorario;
	}

	public void setFechaHoraHorario(Date fechaHoraHorario) {
		this.fechaHoraHorario = fechaHoraHorario;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_HORA_TIMBRE", length = 19)
	public Date getFechaHoraTimbre() {
		return this.fechaHoraTimbre;
	}

	public void setFechaHoraTimbre(Date fechaHoraTimbre) {
		this.fechaHoraTimbre = fechaHoraTimbre;
	}

	@Column(name = "ENTRADA_SALIDA", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getEntradaSalida() {
		return this.entradaSalida;
	}

	public void setEntradaSalida(String entradaSalida) {
		this.entradaSalida = entradaSalida;
	}

	@Column(name = "CODIGO_EMPLEADO", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getCodigoEmpleado() {
		return this.codigoEmpleado;
	}

	public void setCodigoEmpleado(String codigoEmpleado) {
		this.codigoEmpleado = codigoEmpleado;
	}

	@Column(name = "ASIS_ORDEN", nullable = false)
	@NotNull
	public Integer getAsisOrden() {
		return this.asisOrden;
	}

	public void setAsisOrden(Integer asisOrden) {
		this.asisOrden = asisOrden;
	}

	@Column(name = "ASIS_MAX_MINUTO", nullable = false)
	@NotNull
	public int getAsisMaxMinuto() {
		return this.asisMaxMinuto;
	}

	public void setAsisMaxMinuto(int asisMaxMinuto) {
		this.asisMaxMinuto = asisMaxMinuto;
	}

	@Column(name = "ESTADO", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "asistencia")
	public Set<AsistenciaHoraExtra> getAsistenciaHoraExtras() {
		return this.asistenciaHoraExtras;
	}

	public void setAsistenciaHoraExtras(
			Set<AsistenciaHoraExtra> asistenciaHoraExtras) {
		this.asistenciaHoraExtras = asistenciaHoraExtras;
	}

	@Transient
	public Date getFechaDesde() {
		return fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Transient
	public Date getFechaHasta() {
		return fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Override
	public String toString() {
		return "Asistencia [asisId=" + asisId + ", empleado=" + empleado.getCedula()
				+ ", fechaHoraHorario=" + fechaHoraHorario
				+ ", fechaHoraTimbre=" + fechaHoraTimbre + ", entradaSalida="
				+ entradaSalida + ", codigoEmpleado=" + codigoEmpleado
				+ ", asisOrden=" + asisOrden + ", asisMaxMinuto="
				+ asisMaxMinuto + ", estado=" + estado + "]";
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_HORARIO", length = 19)

	public Date getFechaHorario() {
		return fechaHorario;
	}

	public void setFechaHorario(Date fechaHorario) {
		this.fechaHorario = fechaHorario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HORA_HORARIO", length = 19)
	public Date getHoraHorario() {
		return HoraHorario;
	}

	public void setHoraHorario(Date horaHorario) {
		HoraHorario = horaHorario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_TIMBRE", length = 19)
	public Date getFechaTimbre() {
		return fechaTimbre;
	}

	public void setFechaTimbre(Date fechaTimbre) {
		this.fechaTimbre = fechaTimbre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HORA_TIMBRE", length = 19)
	public Date getHoraTimbre() {
		return HoraTimbre;
	}

	public void setHoraTimbre(Date horaTimbre) {
		HoraTimbre = horaTimbre;
	}
	@Column(name = "DEHO_ID_NUEVO")
	public Long getDehoIdNuevo() {
		return dehoIdNuevo;
	}

	public void setDehoIdNuevo(Long dehoIdNuevo) {
		this.dehoIdNuevo = dehoIdNuevo;
	}	
	
	@Column(name = "MODIFICADO")
	public Long getModificado() {
		return modificado;
	}

	public void setModificado(Long modificado) {
		this.modificado = modificado;
	}

	@Column(name = "OBSERVACION")
	public String getObservacion() {
		return observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
}
