package com.casapazmino.fulltime.model;
// Generated 26/09/2011 09:54:50 AM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * AsistenciaHoraExtra generated by hbm2java
 */
@Entity
@Table(name = "asistencia_hora_extra")
public class AsistenciaHoraExtra implements java.io.Serializable {

	private static final long serialVersionUID = 6857495732365045355L;
	
	private Integer asisHoraExtrId;
	private HoraExtra horaExtra;
	private Asistencia asistencia;
	private int autorizadas;

	public AsistenciaHoraExtra() {
	}

	public AsistenciaHoraExtra(HoraExtra horaExtra, Asistencia asistencia,
			int autorizadas) {
		this.horaExtra = horaExtra;
		this.asistencia = asistencia;
		this.autorizadas = autorizadas;
	}

	@Id
	@TableGenerator(name = "IDASISHORAEXTRA", table = "contadores", pkColumnName = "ID", pkColumnValue = "21", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDASISHORAEXTRA")
	@Column(name = "ASIS_HORA_EXTR_ID", unique = true, nullable = false)
	public Integer getAsisHoraExtrId() {
		return this.asisHoraExtrId;
	}

	public void setAsisHoraExtrId(Integer asisHoraExtrId) {
		this.asisHoraExtrId = asisHoraExtrId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA_EXTRA_ID", nullable = false)
	@NotNull
	public HoraExtra getHoraExtra() {
		return this.horaExtra;
	}

	public void setHoraExtra(HoraExtra horaExtra) {
		this.horaExtra = horaExtra;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASIS_ID", nullable = false)
	@NotNull
	public Asistencia getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Asistencia asistencia) {
		this.asistencia = asistencia;
	}

	@Column(name = "AUTORIZADAS", nullable = false)
	@NotNull
	public int getAutorizadas() {
		return this.autorizadas;
	}

	public void setAutorizadas(int autorizadas) {
		this.autorizadas = autorizadas;
	}
}
