package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad")
public class Ciudad implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long ciudId;
	private Provincia provincia;
	private String codigo;
	private String descripcion;
	private Set<CiudadFeriado> ciudadFeriados = new HashSet<CiudadFeriado>(0);
	private Set<Empleado> empleados = new HashSet<Empleado>(0);
	
	private Integer nivel;

	public Ciudad() {
		this.provincia=new Provincia();
	}

	public Ciudad(Provincia provincia, String codigo, String descripcion) {
		this.provincia = provincia;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Ciudad(Provincia provincia, String codigo, String descripcion,
			Set<CiudadFeriado> ciudadFeriados, Set<Empleado> empleados) {
		this.provincia = provincia;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.ciudadFeriados = ciudadFeriados;
		this.empleados = empleados;
	}

	@Id
	@TableGenerator(name = "IDCIUDAD", table = "contadores", pkColumnName = "ID", pkColumnValue = "3", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDCIUDAD")
	@Column(name = "CIUD_ID", unique = true, nullable = false)
	public Long getCiudId() {
		return this.ciudId;
	}

	public void setCiudId(Long ciudId) {
		this.ciudId = ciudId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROV_ID", nullable = false)
	@NotNull
	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Column(name = "CODIGO", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
//	@Duplicado(message = "Código ya existe", componente= "ciudadHome", campo = "codigo", campoId = "ciudId", entidad = "Ciudad")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRIPCION", unique = true, nullable = false)
	@NotNull
//	@Duplicado(message = "Descripción ya existe", componente = "ciudadHome", campo = "descripcion", campoId = "ciudId", entidad = "Ciudad")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<CiudadFeriado> getCiudadFeriados() {
		return this.ciudadFeriados;
	}

	public void setCiudadFeriados(Set<CiudadFeriado> ciudadFeriados) {
		this.ciudadFeriados = ciudadFeriados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	public String cadenaDatos(){
		return this.getCodigo().toString()+","+this.getDescripcion()+","+this.getProvincia().getProvId().toString();
	}

	@Override
	public String toString() {
		return "ciudId=" + ciudId 
				+ ", codigo=" + codigo + ", descripcion=" + descripcion;
	}

	@Column(name = "NIVEL", nullable = false)
	@NotNull
	public Integer getNivel() {
		return nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
}
