package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * CiudadFeriado generated by hbm2java
 */
@Entity
@Table(name = "ciudad_feriado")
public class CiudadFeriado implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long cifeId;
	private Feriado feriado;
	private Ciudad ciudad;

	public CiudadFeriado() {
	}

	public CiudadFeriado(Feriado feriado, Ciudad ciudad) {
		this.feriado = feriado;
		this.ciudad = ciudad;
	}

	@Id
	@TableGenerator(name = "IDCIUDADFERIADO", table = "contadores", pkColumnName = "ID", pkColumnValue = "22", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDCIUDADFERIADO")
	@Column(name = "CIFE_ID", unique = true, nullable = false)
	public Long getCifeId() {
		return this.cifeId;
	}

	public void setCifeId(Long cifeId) {
		this.cifeId = cifeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FERI_ID")
	public Feriado getFeriado() {
		if (feriado == null){
			feriado = new Feriado();
		}	
		return this.feriado;
	}

	public void setFeriado(Feriado feriado) {
		this.feriado = feriado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIUD_ID")
	public Ciudad getCiudad() {
		if (this.ciudad == null){
			ciudad = new Ciudad();
		}
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@Override
	public String toString() {
		return "Id=" + cifeId + ", Ciudad="
				+ ciudad.getDescripcion() + ", Feriado=" + feriado.getDescripcion();
	}
}
