package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "contacto")
public class Contacto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long contId;
	private DetalleTipoParametro detalleTipoParametro;
	private Empleado empleado;
	private String descripcion;

	public Contacto() {
	}

	public Contacto(Empleado empleado) {
		this.empleado = empleado;
	}

	public Contacto(DetalleTipoParametro detalleTipoParametro,
			Empleado empleado, String descripcion) {
		this.detalleTipoParametro = detalleTipoParametro;
		this.empleado = empleado;
		this.descripcion = descripcion;
	}

	@Id
	@TableGenerator(name = "IDCONTACTO", table = "contadores", pkColumnName = "ID", pkColumnValue = "23", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDCONTACTO")
	@Column(name = "CONT_ID", unique = true, nullable = false)
	public Long getContId() {
		return this.contId;
	}

	public void setContId(Long contId) {
		this.contId = contId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTPA_ID")
	public DetalleTipoParametro getDetalleTipoParametro() {
		return this.detalleTipoParametro;
	}

	public void setDetalleTipoParametro(
			DetalleTipoParametro detalleTipoParametro) {
		this.detalleTipoParametro = detalleTipoParametro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "DESCRIPCION")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "Id=" + contId + ", Descripcion="
				+ descripcion;
	}	
}
