package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.Length;
import org.hibernate.validator.Min;
import org.hibernate.validator.NotNull;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long depaId;
	private Departamento departamento;
	private String codigo;
	private String descripcion;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);
	private Set<Departamento> departamentos = new HashSet<Departamento>(0);
	//new variables
	private Empleado empleado;
	private Integer nivel;
	
	private Set<DepartamentoAutorizacion> departamentoAutorizacion = new HashSet<DepartamentoAutorizacion>(0);

	public Departamento() {
	}

	public Departamento(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Departamento(Departamento departamento, String codigo,
			String descripcion, Set<Empleado> empleados,
			Set<Departamento> departamentos,Empleado empleado, Integer nivel,Set<DepartamentoAutorizacion> departamentoAutorizacion) {
		this.departamento = departamento;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.empleados = empleados;
		this.departamentos = departamentos;
		this.empleado=empleado;
		this.nivel=nivel;
		this.departamentoAutorizacion=departamentoAutorizacion;
	}

	@Id
	@TableGenerator(name = "IDDEPARTAMENTO", table = "contadores", pkColumnName = "ID", pkColumnValue = "13", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDDEPARTAMENTO")
	@Column(name = "DEPA_ID", unique = true, nullable = false)
	public Long getDepaId() {
		return this.depaId;
	}

	public void setDepaId(Long depaId) {
		this.depaId = depaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEP_DEPA_ID")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "CODIGO", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}
	
	@Override
	public String toString() {
		return "Id=" + depaId + ", Descripcion="
				+ descripcion;
	}

//new variables
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID")
	public Empleado getEmpleado() {
		/*if( this.empleado==null){
			 this.empleado=new Empleado();
		}*/
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "NIVEL", nullable = false)
	@NotNull
	@Min(1)
	public Integer getNivel() {
		return nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<DepartamentoAutorizacion> getDepartamentoAutorizacion() {
		return this.departamentoAutorizacion;
	}

	public void setDepartamentoAutorizacion(Set<DepartamentoAutorizacion> departamentoAutorizacion) {
		this.departamentoAutorizacion = departamentoAutorizacion;
	}
	
	
	
	
}
