package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * DetalleGrupoContratado generated by hbm2java
 */
@Entity
@Table(name = "detalle_grupo_contratado")
public class DetalleGrupoContratado implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long dgcoId;
	private GrupoContratado grupoContratado;
	private String descripcion;
	private short horasVacacion;
	private double diasIncremento;
	private short anios;
	private double totalHoras;
	private short maximoHoras;
	private int mesesPeriodo;
	
	private BigDecimal porcentaje;
	private BigDecimal porcentaje1;
	private BigDecimal porcentaje2;
	private BigDecimal porcentaje3;
	private BigDecimal porcentaje4;
	
	private Integer horas_laborables;
	private Integer horas_suplementarias;
	private Integer horas_extraordinarias;
	
	private Integer horas_adicional;
	private Integer horas_adicional1;
	
	private Integer nivel;
	
	private Boolean activarRegla;
	private Integer diasLaborables;
	private Integer diasLibres;
	private Boolean activarFeriados;
	private Boolean activarRecuperable;
	private Boolean solicitudVacacion;
	private Boolean permisoCargo;
	
	private Integer maximo_hora_extra;
	private Integer maximo_horas_semanales;
	
	private Integer limite_aviso;

	
	private Set<Empleado> empleados = new HashSet<Empleado>(0);
	private Set<DetalleHorarioHoraExtra> detalleHorarioHoraExtras = new HashSet<DetalleHorarioHoraExtra>(
			0);

	public DetalleGrupoContratado() {
	}

	public DetalleGrupoContratado(GrupoContratado grupoContratado,
			String descripcion, short horasVacacion, double diasIncremento,
			short anios, short maximoHoras, int mesesPeriodo,BigDecimal porcentaje,
			BigDecimal porcentaje1,BigDecimal porcentaje2,BigDecimal porcentaje3,BigDecimal porcentaje4,
			Integer horas_laborables, Integer horas_suplementarias,Integer horas_extraordinarias, Integer horas_adicional,
			Integer horas_adicional1, Integer horas_adicional2, Integer nivel) {
		this.grupoContratado = grupoContratado;
		this.descripcion = descripcion;
		this.horasVacacion = horasVacacion;
		this.diasIncremento = diasIncremento;
		this.anios = anios;
		this.maximoHoras = maximoHoras;
		this.mesesPeriodo = mesesPeriodo;
		this.porcentaje=porcentaje;
		this.porcentaje1=porcentaje1;
		this.porcentaje2=porcentaje2;
		this.porcentaje3=porcentaje3;
		this.porcentaje4=porcentaje4;
		this.horas_laborables=horas_laborables;
		this.horas_suplementarias=horas_suplementarias;
		this.horas_extraordinarias=horas_extraordinarias;
		this.horas_adicional=horas_adicional;
		this.horas_adicional1=horas_adicional1;
		this.nivel=nivel;
	}
	public DetalleGrupoContratado(GrupoContratado grupoContratado,
			String descripcion, short horasVacacion, double diasIncremento,
			short anios, Short totalHoras, short maximoHoras, int mesesPeriodo,
			Set<Empleado> empleados, Set<DetalleHorarioHoraExtra> detalleHorarioHoraExtras,BigDecimal porcentaje,
			BigDecimal porcentaje1,BigDecimal porcentaje2,BigDecimal porcentaje3,BigDecimal porcentaje4,
			Integer horas_laborables, Integer horas_suplementarias,Integer horas_extraordinarias, Integer horas_adicional,
			Integer horas_adicional1, Integer horas_adicional2, Integer nivel) {
		this.grupoContratado = grupoContratado;
		this.descripcion = descripcion;
		this.horasVacacion = horasVacacion;
		this.diasIncremento = diasIncremento;
		this.anios = anios;
		this.totalHoras = totalHoras;
		this.maximoHoras = maximoHoras;
		this.mesesPeriodo = mesesPeriodo;
		this.empleados = empleados;
		this.detalleHorarioHoraExtras = detalleHorarioHoraExtras;
		this.porcentaje=porcentaje;
		this.porcentaje1=porcentaje1;
		this.porcentaje2=porcentaje2;
		this.porcentaje3=porcentaje3;
		this.porcentaje4=porcentaje4;
		this.horas_laborables=horas_laborables;
		this.horas_suplementarias=horas_suplementarias;
		this.horas_extraordinarias=horas_extraordinarias;
		this.horas_adicional=horas_adicional;
		this.horas_adicional1=horas_adicional1;
		this.nivel=nivel;
	}


	@Id
	@TableGenerator(name = "IDDETGRUCONTRATO", table = "contadores", pkColumnName = "ID", pkColumnValue = "17", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDDETGRUCONTRATO")
	@Column(name = "DGCO_ID", unique = true, nullable = false)
	public Long getDgcoId() {
		return this.dgcoId;
	}

	public void setDgcoId(Long dgcoId) {
		this.dgcoId = dgcoId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRCO_ID", nullable = false)
	@NotNull
	public GrupoContratado getGrupoContratado() {
		return this.grupoContratado;
	}

	public void setGrupoContratado(GrupoContratado grupoContratado) {
		this.grupoContratado = grupoContratado;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "HORAS_VACACION", nullable = false)
	@NotNull
	public short getHorasVacacion() {
		return this.horasVacacion;
	}

	public void setHorasVacacion(short horasVacacion) {
		this.horasVacacion = horasVacacion;
	}

	@Column(name = "DIAS_INCREMENTO", nullable = false)
	@NotNull
	public double getDiasIncremento() {
		return this.diasIncremento;
	}

	public void setDiasIncremento(double diasIncremento) {
		this.diasIncremento = diasIncremento;
	}

	@Column(name = "ANIOS", nullable = false)
	@NotNull
	public short getAnios() {
		return this.anios;
	}

	public void setAnios(short anios) {
		this.anios = anios;
	}

	@Column(name = "TOTAL_HORAS")
	public double getTotalHoras() {
		return this.totalHoras;
	}

	public void setTotalHoras(double totalHoras) {
		this.totalHoras = totalHoras;
	}

	@Column(name = "MAXIMO_HORAS", nullable = false)
	@NotNull
	public short getMaximoHoras() {
		return this.maximoHoras;
	}

	public void setMaximoHoras(short maximoHoras) {
		this.maximoHoras = maximoHoras;
	}

	@Column(name = "MESES_PERIODO", nullable = false)
	@NotNull
	public int getMesesPeriodo() {
		return this.mesesPeriodo;
	}

	public void setMesesPeriodo(int mesesPeriodo) {
		this.mesesPeriodo = mesesPeriodo;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "detalleGrupoContratado")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "detalleGrupoContratado")
	public Set<DetalleHorarioHoraExtra> getDetalleHorarioHoraExtras() {
		return this.detalleHorarioHoraExtras;
	}

	public void setDetalleHorarioHoraExtras(Set<DetalleHorarioHoraExtra> detalleHorarioHoraExtras) {
		this.detalleHorarioHoraExtras = detalleHorarioHoraExtras;
	}
	
	@Column(name = "PORCENTAJE", nullable = true, precision = 4)
//	@NotNull
//	@Min(0)
	public BigDecimal getPorcentaje() {
		return porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "PORCENTAJE1", nullable = true, precision = 4)
//	@NotNull
//	@Min(0)
	public BigDecimal getPorcentaje1() {
		return porcentaje1;
	}

	public void setPorcentaje1(BigDecimal porcentaje1) {
		this.porcentaje1 = porcentaje1;
	}

	@Column(name = "PORCENTAJE2", nullable = true, precision = 4)
//	@NotNull
//	@Min(0)
	public BigDecimal getPorcentaje2() {
		return porcentaje2;
	}

	public void setPorcentaje2(BigDecimal porcentaje2) {
		this.porcentaje2 = porcentaje2;
	}

	@Column(name = "PORCENTAJE3", nullable = true, precision = 4)
//	@NotNull
//	@Min(0)
	public BigDecimal getPorcentaje3() {
		return porcentaje3;
	}

	public void setPorcentaje3(BigDecimal porcentaje3) {
		this.porcentaje3 = porcentaje3;
	}

	@Column(name = "PORCENTAJE4", nullable = true, precision = 4)
//	@NotNull
//	@Min(0)
	public BigDecimal getPorcentaje4() {
		return porcentaje4;
	}

	public void setPorcentaje4(BigDecimal porcentaje4) {
		this.porcentaje4 = porcentaje4;
	}
	
	@Column(name = "HORAS_LABORABLES", nullable = true)
//	@NotNull
	public Integer getHoras_laborables() {
		return horas_laborables;
	}

	public void setHoras_laborables(Integer horas_laborables) {
		this.horas_laborables = horas_laborables;
	}

	@Column(name = "HORAS_SUPLEMENTARIAS", nullable = true)
//	@NotNull
	public Integer getHoras_suplementarias() {
		return horas_suplementarias;
	}

	public void setHoras_suplementarias(Integer horas_suplementarias) {
		this.horas_suplementarias = horas_suplementarias;
	}

	@Column(name = "HORAS_EXTRAORDINARIAS", nullable = true)
//	@NotNull
	public Integer getHoras_extraordinarias() {
		return horas_extraordinarias;
	}

	public void setHoras_extraordinarias(Integer horas_extraordinarias) {
		this.horas_extraordinarias = horas_extraordinarias;
	}

	@Column(name = "HORAS_ADICIONAL", nullable = true)
//	@NotNull
	public Integer getHoras_adicional() {
		return horas_adicional;
	}

	public void setHoras_adicional(Integer horas_adicional) {
		this.horas_adicional = horas_adicional;
	}

	@Column(name = "HORAS_ADICIONAL1", nullable = true)
//	@NotNull
	public Integer getHoras_adicional1() {
		return horas_adicional1;
	}

	public void setHoras_adicional1(Integer horas_adicional1) {
		this.horas_adicional1 = horas_adicional1;
	}
	
	@Column(name = "NIVEL", nullable = true)
//	@NotNull
	public Integer getNivel() {
		return nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}	
	
	@Override
	public String toString() {
		return "Id=" + dgcoId + ", Descripcion="
				+ descripcion + ", Dias Incremento=" + diasIncremento
				+ ", Anios=" + anios
				+ ", Dias Vacacion=" + horasVacacion
				+ ", Max.Horas=" + maximoHoras
				+ ", Meses Periodo=" + mesesPeriodo
				+ ", Total Dias=" + totalHoras;
	}

	@Column(name = "ACTIVAR_REGLA", nullable = true)
	public Boolean getActivarRegla() {
		return activarRegla;
	}

	public void setActivarRegla(Boolean activarRegla) {
		this.activarRegla = activarRegla;
	}

	@Column(name = "DIAS_LABORABLES", nullable = true)
	public Integer getDiasLaborables() {
		return diasLaborables;
	}

	public void setDiasLaborables(Integer diasLaborables) {
		this.diasLaborables = diasLaborables;
	}

	@Column(name = "DIAS_LIBRES", nullable = true)
	public Integer getDiasLibres() {
		return diasLibres;
	}

	public void setDiasLibres(Integer diasLibres) {
		this.diasLibres = diasLibres;
	}

	@Column(name = "ACTIVAR_FERIADOS", nullable = true)
	public Boolean getActivarFeriados() {
		return activarFeriados;
	}

	public void setActivarFeriados(Boolean activarFeriados) {
		this.activarFeriados = activarFeriados;
	}

	@Column(name = "SOLICITUD_VACACION", nullable = true)
	public Boolean getSolicitudVacacion() {
		return solicitudVacacion;
	}

	public void setSolicitudVacacion(Boolean solicitudVacacion) {
		this.solicitudVacacion = solicitudVacacion;
	}

	@Column(name = "PERMISO_CARGO", nullable = true)
	public Boolean getPermisoCargo() {
		return permisoCargo;
	}

	public void setPermisoCargo(Boolean permisoCargo) {
		this.permisoCargo = permisoCargo;
	}

	@Column(name = "ACTIVAR_RECUPERABLE", nullable = true)
	public Boolean getActivarRecuperable() {
		return activarRecuperable;
	}

	public void setActivarRecuperable(Boolean activarRecuperable) {
		this.activarRecuperable = activarRecuperable;
	}

	@Column(name = "MAXIMO_HORAS_EXTRA", nullable = false)
	public Integer getMaximo_hora_extra() {
		return maximo_hora_extra;
	}

	public void setMaximo_hora_extra(Integer maximo_hora_extra) {
		this.maximo_hora_extra = maximo_hora_extra;
	}
	
	@Column(name = "MAXIMO_HORAS_SEMANAL", nullable = false)
	public Integer getMaximo_horas_semanales() {
		return maximo_horas_semanales;
	}

	public void setMaximo_horas_semanales(Integer maximo_horas_semanales) {
		this.maximo_horas_semanales = maximo_horas_semanales;
	}
	
	@Column(name = "HORAS_AVISO", nullable = false)
	public Integer getLimite_aviso() {
		return limite_aviso;
	}

	public void setLimite_aviso(Integer limite_aviso) {
		this.limite_aviso = limite_aviso;
	}	
	
}
