package com.casapazmino.fulltime.model;
// Generated 23/11/2011 03:44:10 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * DetalleHorarioHoraExtra generated by hbm2java
 */
@Entity
@Table(name = "detalle_horario_hora_extra")
public class DetalleHorarioHoraExtra implements java.io.Serializable {

	private static final long serialVersionUID = 2516992982849880355L;
	private Integer dhheId;
	private HoraExtra horaExtra;
	private DetalleHorario detalleHorario;
	private DetalleGrupoContratado detalleGrupoContratado;
	
	public DetalleHorarioHoraExtra() {
	}

	public DetalleHorarioHoraExtra(HoraExtra horaExtra,
			DetalleHorario detalleHorario, DetalleGrupoContratado detalleGrupoContratado) {
		this.horaExtra = horaExtra;
		this.detalleHorario = detalleHorario;
		this.detalleGrupoContratado = detalleGrupoContratado;
	}
	
	@Id
	@TableGenerator(name = "IDDETHORHORAEXTRA", table = "contadores", pkColumnName = "ID", pkColumnValue = "11", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDDETHORHORAEXTRA")
	@Column(name = "DHHE_ID", unique = true, nullable = false)
	public Integer getDhheId() {
		return this.dhheId;
	}

	public void setDhheId(Integer dhheId) {
		this.dhheId = dhheId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA_EXTRA_ID", nullable = false)
	@NotNull
	public HoraExtra getHoraExtra() {
		if(horaExtra == null){
			horaExtra = new HoraExtra();
		}
		return this.horaExtra;
	}

	public void setHoraExtra(HoraExtra horaExtra) {
		this.horaExtra = horaExtra;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEHO_ID", nullable = false)
	@NotNull
	public DetalleHorario getDetalleHorario() {
		if(detalleHorario == null){
			detalleHorario = new DetalleHorario();
		}
		return this.detalleHorario;
	}

	public void setDetalleHorario(DetalleHorario detalleHorario) {
		this.detalleHorario = detalleHorario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DGCO_ID", nullable = false)
	@NotNull
	public DetalleGrupoContratado getDetalleGrupoContratado() {
		if (detalleGrupoContratado == null){
			detalleGrupoContratado = new DetalleGrupoContratado();
		}
		return this.detalleGrupoContratado;
	}

	public void setDetalleGrupoContratado(
			DetalleGrupoContratado detalleGrupoContratado) {
		this.detalleGrupoContratado = detalleGrupoContratado;
	}

	@Override
	public String toString() {
		return "dhheId=" + dhheId + ", horaExtra="
				+ horaExtra.getDescripcion() + ", detalleHorario=" + detalleHorario.getDehoId()
				+ ", detalleGrupoContratado=" + detalleGrupoContratado.getDescripcion();
	}
	

}
