package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * DetalleHorario generated by hbm2java
 */
@Entity
@Table(name = "detalle_tipo_permiso")
public class DetalleTipoPermiso implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long dtpeId;
	private TipoPermiso tipoPermiso;
	private Integer inicio;
	private Integer fin;
	private String tipo;
	private Integer nivel;
	
	public DetalleTipoPermiso() {
	}

	public DetalleTipoPermiso(Long dtpeId, TipoPermiso tipoPermiso, Integer inicio, Integer fin, String tipo, Integer nivel) {
		this.setDtpeId(dtpeId);
		this.setTipoPermiso(tipoPermiso);
		this.setInicio(inicio);
		this.setFin(fin);
		this.setTipo(tipo);
		this.setNivel(nivel);
	}

	@Id
	@TableGenerator(name = "IDDETALLETIPOPERMISO", table = "contadores", pkColumnName = "ID", pkColumnValue = "56", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDDETALLETIPOPERMISO")
	@Column(name = "DTPE_ID", unique = true, nullable = false)
	public Long getDtpeId() {
		return dtpeId;
	}

	public void setDtpeId(Long dtpeId) {
		this.dtpeId = dtpeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPE_ID", nullable = false)
	@NotNull
	public TipoPermiso getTipoPermiso() {
		if (tipoPermiso == null) {
			tipoPermiso = new TipoPermiso();
			}
		return tipoPermiso;
	}

	public void setTipoPermiso(TipoPermiso tipoPermiso) {
		this.tipoPermiso = tipoPermiso;
	}

	@Column(name = "INICIO", nullable = false)
	@NotNull
	public Integer getInicio() {
		return inicio;
	}

	public void setInicio(Integer inicio) {
		this.inicio = inicio;
	}

	@Column(name = "FIN", nullable = false)
	@NotNull
	public Integer getFin() {
		return fin;
	}

	public void setFin(Integer fin) {
		this.fin = fin;
	}

	@Column(name = "TIPO", nullable = false)
	@NotNull
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "NIVEL", nullable = false)
	@NotNull
	public Integer getNivel() {
		return nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
	

}