package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DetalleHorario generated by hbm2java
 */
@Entity
@Table(name = "detalle_horario")
public class DetalleHorario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long dehoId;
	private Horario horario;
	private byte orden;
	private String entradaSalida;
	private Date hora;
	private int maxMinuto;
	private boolean nocturno;
	private boolean especial;
	
	private Set<DetalleHorarioHoraExtra> detalleHorarioHoraExtras = new HashSet<DetalleHorarioHoraExtra>(
			0);
	private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

	public DetalleHorario() {
	}

	public DetalleHorario(Horario horario, byte orden, String entradaSalida,
			Date hora, int maxMinuto, boolean nocturno, boolean especial) {
		this.horario = horario;
		this.orden = orden;
		this.entradaSalida = entradaSalida;
		this.hora = hora;
		this.maxMinuto = maxMinuto;
		this.nocturno = nocturno;
		this.especial = especial;
	}
	public DetalleHorario(Horario horario, byte orden, String entradaSalida,
			Date hora, int maxMinuto, boolean nocturno, boolean especial,
			Set<DetalleHorarioHoraExtra> detalleHorarioHoraExtras,
			Set<Asistencia> asistencias) {
		this.horario = horario;
		this.orden = orden;
		this.entradaSalida = entradaSalida;
		this.hora = hora;
		this.maxMinuto = maxMinuto;
		this.nocturno = nocturno;
		this.detalleHorarioHoraExtras = detalleHorarioHoraExtras;
		this.asistencias = asistencias;
		this.especial = especial;
	}

	@Id
	@TableGenerator(name = "IDDETALLEHORARIO", table = "contadores", pkColumnName = "ID", pkColumnValue = "10", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDDETALLEHORARIO")
	@Column(name = "DEHO_ID", unique = true, nullable = false)
	public Long getDehoId() {
		return this.dehoId;
	}

	public void setDehoId(Long dehoId) {
		this.dehoId = dehoId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA_ID", nullable = false)
	@NotNull
	public Horario getHorario() {
		if (horario == null) {
			horario = new Horario();
			}
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@Column(name = "ORDEN", nullable = false)
	@NotNull
	public byte getOrden() {
		return this.orden;
	}

	public void setOrden(byte orden) {
		this.orden = orden;
	}

	@Column(name = "ENTRADA_SALIDA", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getEntradaSalida() {
		return this.entradaSalida;
	}

	public void setEntradaSalida(String entradaSalida) {
		this.entradaSalida = entradaSalida;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HORA", nullable = false, length = 19)
	@NotNull
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "MAX_MINUTO", nullable = false)
	@NotNull
	public int getMaxMinuto() {
		return this.maxMinuto;
	}

	public void setMaxMinuto(int maxMinuto) {
		this.maxMinuto = maxMinuto;
	}

	@Column(name = "NOCTURNO", nullable = false)
	@NotNull
	public boolean isNocturno() {
		return nocturno;
	}

	public void setNocturno(boolean nocturno) {
		this.nocturno = nocturno;
	}

	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "detalleHorario")
	public Set<DetalleHorarioHoraExtra> getDetalleHorarioHoraExtras() {
		return this.detalleHorarioHoraExtras;
	}

	public void setDetalleHorarioHoraExtras(
			Set<DetalleHorarioHoraExtra> detalleHorarioHoraExtras) {
		this.detalleHorarioHoraExtras = detalleHorarioHoraExtras;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "detalleHorario")
	public Set<Asistencia> getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set<Asistencia> asistencias) {
		this.asistencias = asistencias;
	}

	@Column(name = "ESPECIAL", nullable = false)
	@NotNull
	public boolean isEspecial() {
		return especial;
	}

	public void setEspecial(boolean especial) {
		this.especial = especial;
	}

	@Override
	public String toString() {
		return "dehoId=" + dehoId + ", orden=" + orden
				+ ", entradaSalida=" + entradaSalida + ", hora=" + hora
				+ ", maxMinuto=" + maxMinuto + ", nocturno=" + nocturno;
	}
	
}
