package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * Discapacidad generated by hbm2java
 */
@Entity
@Table(name = "discapacidad")
public class Discapacidad implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long discId;
	private Empleado empleado;
	private String carnetConadis;
	private String porcentaje;
	private String tipo;

	public Discapacidad() {
	}

	public Discapacidad(Empleado empleado, String carnetConadis,
			String porcentaje, String tipo) {
		this.empleado = empleado;
		this.carnetConadis = carnetConadis;
		this.porcentaje = porcentaje;
		this.tipo = tipo;
	}

	@Id
	@TableGenerator(name = "IDDISCAPACIDAD", table = "contadores", pkColumnName = "ID", pkColumnValue = "25", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDDISCAPACIDAD")
	@Column(name = "DISC_ID", unique = true, nullable = false)
	public Long getDiscId() {
		return this.discId;
	}

	public void setDiscId(Long discId) {
		this.discId = discId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID")
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "CARNET_CONADIS")
	public String getCarnetConadis() {
		return this.carnetConadis;
	}

	public void setCarnetConadis(String carnetConadis) {
		this.carnetConadis = carnetConadis;
	}

	@Column(name = "PORCENTAJE", precision = 6)
	public String getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(String porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "TIPO")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Override
	public String toString() {
		return "discId=" + discId + ", empleado=" + empleado.getCodigoEmpleado()
				+ ", carnetConadis=" + carnetConadis + ", porcentaje="
				+ porcentaje + ", tipo=" + tipo;
	}

}
