package com.casapazmino.fulltime.model;
// Generated 10/01/2011 11:40:10 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * EmpleadoTitulo generated by hbm2java
 */
@Entity
@Table(name = "empleado_titulo")
public class EmpleadoTitulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long emtiId;
	private Titulo titulo;
	private DetalleTipoParametro detalleTipoParametro;
	private Empleado empleado;

	public EmpleadoTitulo() {
		this.titulo=new Titulo();
		this.detalleTipoParametro=new DetalleTipoParametro();
		this.empleado=new Empleado();
	}

	public EmpleadoTitulo(Titulo titulo,
			DetalleTipoParametro detalleTipoParametro, Empleado empleado) {
		this.titulo = titulo;
		this.detalleTipoParametro = detalleTipoParametro;
		this.empleado = empleado;
	}

	@Id
	@TableGenerator(name = "IDEMPTITULO", table = "contadores", pkColumnName = "ID", pkColumnValue = "27", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDEMPTITULO")
	@Column(name = "EMTI_ID", unique = true, nullable = false)
	public Long getEmtiId() {
		return this.emtiId;
	}

	public void setEmtiId(Long emtiId) {
		this.emtiId = emtiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TITU_ID", nullable = false)
	@NotNull
	public Titulo getTitulo() {
		return this.titulo;
	}

	public void setTitulo(Titulo titulo) {
		this.titulo = titulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NIVEL", nullable = false)
	@NotNull
	public DetalleTipoParametro getDetalleTipoParametro() {
		return this.detalleTipoParametro;
	}

	public void setDetalleTipoParametro(
			DetalleTipoParametro detalleTipoParametro) {
		this.detalleTipoParametro = detalleTipoParametro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID")
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Override
	public String toString() {
		return "emtiId=" + emtiId + ", titulo=" + titulo.getDescripcion()
				+ ", detalleTipoParametro=" + detalleTipoParametro.getDescripcion()
				+ ", empleado=" + empleado.getCodigoEmpleado();
	}

}
