package com.casapazmino.fulltime.model;
// Generated 08/05/2015 10:45:50 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * HistLabo generated by hbm2java
 */
@Entity
@Table(name = "hist_labo")
public class HistLabo implements java.io.Serializable {

	private static final long serialVersionUID = 6003956926986568828L;
	private Integer hilaId;
	private Empleado empleado;
	private Date fechaIngreso;
	private Date fechaSalida;
	private Boolean estado;
	private Set<EmpleadoPeriodoVacacion> empleadoPeriodoVacacions = new HashSet<EmpleadoPeriodoVacacion>(
			0);

	public HistLabo() {
	}

	public HistLabo(Empleado empleado, Date fechaIngreso, Boolean estado) {
		this.empleado = empleado;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
	}

	public HistLabo(Empleado empleado, Date fechaIngreso, Date fechaSalida, Boolean estado,
			Set<EmpleadoPeriodoVacacion> empleadoPeriodoVacacions) {
		this.empleado = empleado;
		this.fechaIngreso = fechaIngreso;
		this.fechaSalida = fechaSalida;
		this.estado = estado;
		this.empleadoPeriodoVacacions = empleadoPeriodoVacacions;
	}

	@Id
	@TableGenerator(name = "IDHISTLABO", table = "contadores", pkColumnName = "ID", pkColumnValue = "51", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDHISTLABO")	
	@Column(name = "HILA_ID", unique = true, nullable = false)
	public Integer getHilaId() {
		return this.hilaId;
	}

	public void setHilaId(Integer hilaId) {
		this.hilaId = hilaId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INGRESO", nullable = false, length = 10)
	@NotNull
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_SALIDA", length = 10)
	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}
	
	@Column(name = "ESTADO", nullable = false)
	@NotNull
	public Boolean getEstado() {
		return estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "histLabo")
	public Set<EmpleadoPeriodoVacacion> getEmpleadoPeriodoVacacions() {
		return this.empleadoPeriodoVacacions;
	}

	public void setEmpleadoPeriodoVacacions(
			Set<EmpleadoPeriodoVacacion> empleadoPeriodoVacacions) {
		this.empleadoPeriodoVacacions = empleadoPeriodoVacacions;
	}


}
