package com.casapazmino.fulltime.model;
// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario")
public class Horario implements java.io.Serializable {

	private static final long serialVersionUID = 6660776613060993961L;

	private Long horaId;
	private String descripcion;
	private Integer almuerzoMinutos;
	private String estado;
	private String codigo;
	private Integer horasTrabajo;
	
	private Set<Planificacion> planificacionsForHora11Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora12Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora9Id = new HashSet<Planificacion>(
			0);
	private Set<SolicitudVacacion> solicitudVacacions = new HashSet<SolicitudVacacion>(
			0);
	private Set<Planificacion> planificacionsForHora10Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora15Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora16Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora31Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora13Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora14Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora29Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora30Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora28Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora8Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora17Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora24Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora25Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora26Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora27Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora1Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora2Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora20Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora3Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora21Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora4Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora22Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora5Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora23Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora18Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora19Id = new HashSet<Planificacion>(
			0);
	private Set<DetalleHorario> detalleHorarios = new HashSet<DetalleHorario>(0);
	
	private Set<Planificacion> planificacionsForHora7Id = new HashSet<Planificacion>(
			0);
	private Set<Planificacion> planificacionsForHora6Id = new HashSet<Planificacion>(
			0);
	
	private Set<EmpleadoHorario> empleadoHorarios = new HashSet<EmpleadoHorario>(0);

	public Horario() {
	}

	public Horario(String descripcion) {
		this.descripcion = descripcion;
	}
	public Horario(String descripcion, Integer almuerzoMinutos, Set<EmpleadoHorario> empleadoHorarios,
			Set<Planificacion> planificacionsForHora11Id,
			Set<Planificacion> planificacionsForHora12Id,
			Set<Planificacion> planificacionsForHora9Id,
			Set<SolicitudVacacion> solicitudVacacions,
			Set<Planificacion> planificacionsForHora10Id,
			Set<Planificacion> planificacionsForHora15Id,
			Set<Planificacion> planificacionsForHora16Id,
			Set<Planificacion> planificacionsForHora31Id,
			Set<Planificacion> planificacionsForHora13Id,
			Set<Planificacion> planificacionsForHora14Id,
			Set<Planificacion> planificacionsForHora29Id,
			Set<Planificacion> planificacionsForHora30Id,
			Set<Planificacion> planificacionsForHora28Id,
			Set<Planificacion> planificacionsForHora8Id,
			Set<Planificacion> planificacionsForHora17Id,
			Set<Planificacion> planificacionsForHora24Id,
			Set<Planificacion> planificacionsForHora25Id,
			Set<Planificacion> planificacionsForHora26Id,
			Set<Planificacion> planificacionsForHora27Id,
			Set<Planificacion> planificacionsForHora1Id,
			Set<Planificacion> planificacionsForHora2Id,
			Set<Planificacion> planificacionsForHora20Id,
			Set<Planificacion> planificacionsForHora3Id,
			Set<Planificacion> planificacionsForHora21Id,
			Set<Planificacion> planificacionsForHora4Id,
			Set<Planificacion> planificacionsForHora22Id,
			Set<Planificacion> planificacionsForHora5Id,
			Set<Planificacion> planificacionsForHora23Id,
			Set<Planificacion> planificacionsForHora18Id,
			Set<Planificacion> planificacionsForHora19Id,
			Set<DetalleHorario> detalleHorarios,
			Set<Planificacion> planificacionsForHora7Id,
			Set<Planificacion> planificacionsForHora6Id, String estado, String codigo, Integer horasTrabajo) {
		this.empleadoHorarios = empleadoHorarios;
		this.descripcion = descripcion;
		this.almuerzoMinutos = almuerzoMinutos;
		this.estado=estado;
		this.codigo=codigo;
		this.horasTrabajo = horasTrabajo;
		this.planificacionsForHora11Id = planificacionsForHora11Id;
		this.planificacionsForHora12Id = planificacionsForHora12Id;
		this.planificacionsForHora9Id = planificacionsForHora9Id;
		this.solicitudVacacions = solicitudVacacions;
		this.planificacionsForHora10Id = planificacionsForHora10Id;
		this.planificacionsForHora15Id = planificacionsForHora15Id;
		this.planificacionsForHora16Id = planificacionsForHora16Id;
		this.planificacionsForHora31Id = planificacionsForHora31Id;
		this.planificacionsForHora13Id = planificacionsForHora13Id;
		this.planificacionsForHora14Id = planificacionsForHora14Id;
		this.planificacionsForHora29Id = planificacionsForHora29Id;
		this.planificacionsForHora30Id = planificacionsForHora30Id;
		this.planificacionsForHora28Id = planificacionsForHora28Id;
		this.planificacionsForHora8Id = planificacionsForHora8Id;
		this.planificacionsForHora17Id = planificacionsForHora17Id;
		this.planificacionsForHora24Id = planificacionsForHora24Id;
		this.planificacionsForHora25Id = planificacionsForHora25Id;
		this.planificacionsForHora26Id = planificacionsForHora26Id;
		this.planificacionsForHora27Id = planificacionsForHora27Id;
		this.planificacionsForHora1Id = planificacionsForHora1Id;
		this.planificacionsForHora2Id = planificacionsForHora2Id;
		this.planificacionsForHora20Id = planificacionsForHora20Id;
		this.planificacionsForHora3Id = planificacionsForHora3Id;
		this.planificacionsForHora21Id = planificacionsForHora21Id;
		this.planificacionsForHora4Id = planificacionsForHora4Id;
		this.planificacionsForHora22Id = planificacionsForHora22Id;
		this.planificacionsForHora5Id = planificacionsForHora5Id;
		this.planificacionsForHora23Id = planificacionsForHora23Id;
		this.planificacionsForHora18Id = planificacionsForHora18Id;
		this.planificacionsForHora19Id = planificacionsForHora19Id;
		this.detalleHorarios = detalleHorarios;
		this.planificacionsForHora7Id = planificacionsForHora7Id;
		this.planificacionsForHora6Id = planificacionsForHora6Id;
	}

	@Id
	@TableGenerator(name = "IDHORARIO", table = "contadores", pkColumnName = "ID", pkColumnValue = "9", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDHORARIO")
	@Column(name = "HORA_ID", unique = true, nullable = false)
	public Long getHoraId() {
		return this.horaId;
	}

	public void setHoraId(Long horaId) {
		this.horaId = horaId;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "CODIGO", nullable = false)
	@NotNull
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "ALMUERZO_MINUTOS")
	@NotNull	
	public Integer getAlmuerzoMinutos() {
		return this.almuerzoMinutos;
	}

	public void setAlmuerzoMinutos(Integer almuerzoMinutos) {
		this.almuerzoMinutos = almuerzoMinutos;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora11Id")
	public Set<Planificacion> getPlanificacionsForHora11Id() {
		return this.planificacionsForHora11Id;
	}

	public void setPlanificacionsForHora11Id(
			Set<Planificacion> planificacionsForHora11Id) {
		this.planificacionsForHora11Id = planificacionsForHora11Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora12Id")
	public Set<Planificacion> getPlanificacionsForHora12Id() {
		return this.planificacionsForHora12Id;
	}

	public void setPlanificacionsForHora12Id(
			Set<Planificacion> planificacionsForHora12Id) {
		this.planificacionsForHora12Id = planificacionsForHora12Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora9Id")
	public Set<Planificacion> getPlanificacionsForHora9Id() {
		return this.planificacionsForHora9Id;
	}

	public void setPlanificacionsForHora9Id(
			Set<Planificacion> planificacionsForHora9Id) {
		this.planificacionsForHora9Id = planificacionsForHora9Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<SolicitudVacacion> getSolicitudVacacions() {
		return this.solicitudVacacions;
	}

	public void setSolicitudVacacions(Set<SolicitudVacacion> solicitudVacacions) {
		this.solicitudVacacions = solicitudVacacions;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora10Id")
	public Set<Planificacion> getPlanificacionsForHora10Id() {
		return this.planificacionsForHora10Id;
	}

	public void setPlanificacionsForHora10Id(
			Set<Planificacion> planificacionsForHora10Id) {
		this.planificacionsForHora10Id = planificacionsForHora10Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora15Id")
	public Set<Planificacion> getPlanificacionsForHora15Id() {
		return this.planificacionsForHora15Id;
	}

	public void setPlanificacionsForHora15Id(
			Set<Planificacion> planificacionsForHora15Id) {
		this.planificacionsForHora15Id = planificacionsForHora15Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora16Id")
	public Set<Planificacion> getPlanificacionsForHora16Id() {
		return this.planificacionsForHora16Id;
	}

	public void setPlanificacionsForHora16Id(
			Set<Planificacion> planificacionsForHora16Id) {
		this.planificacionsForHora16Id = planificacionsForHora16Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora31Id")
	public Set<Planificacion> getPlanificacionsForHora31Id() {
		return this.planificacionsForHora31Id;
	}

	public void setPlanificacionsForHora31Id(
			Set<Planificacion> planificacionsForHora31Id) {
		this.planificacionsForHora31Id = planificacionsForHora31Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora13Id")
	public Set<Planificacion> getPlanificacionsForHora13Id() {
		return this.planificacionsForHora13Id;
	}

	public void setPlanificacionsForHora13Id(
			Set<Planificacion> planificacionsForHora13Id) {
		this.planificacionsForHora13Id = planificacionsForHora13Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora14Id")
	public Set<Planificacion> getPlanificacionsForHora14Id() {
		return this.planificacionsForHora14Id;
	}

	public void setPlanificacionsForHora14Id(
			Set<Planificacion> planificacionsForHora14Id) {
		this.planificacionsForHora14Id = planificacionsForHora14Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora29Id")
	public Set<Planificacion> getPlanificacionsForHora29Id() {
		return this.planificacionsForHora29Id;
	}

	public void setPlanificacionsForHora29Id(
			Set<Planificacion> planificacionsForHora29Id) {
		this.planificacionsForHora29Id = planificacionsForHora29Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora30Id")
	public Set<Planificacion> getPlanificacionsForHora30Id() {
		return this.planificacionsForHora30Id;
	}

	public void setPlanificacionsForHora30Id(
			Set<Planificacion> planificacionsForHora30Id) {
		this.planificacionsForHora30Id = planificacionsForHora30Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora28Id")
	public Set<Planificacion> getPlanificacionsForHora28Id() {
		return this.planificacionsForHora28Id;
	}

	public void setPlanificacionsForHora28Id(
			Set<Planificacion> planificacionsForHora28Id) {
		this.planificacionsForHora28Id = planificacionsForHora28Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora8Id")
	public Set<Planificacion> getPlanificacionsForHora8Id() {
		return this.planificacionsForHora8Id;
	}

	public void setPlanificacionsForHora8Id(
			Set<Planificacion> planificacionsForHora8Id) {
		this.planificacionsForHora8Id = planificacionsForHora8Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora17Id")
	public Set<Planificacion> getPlanificacionsForHora17Id() {
		return this.planificacionsForHora17Id;
	}

	public void setPlanificacionsForHora17Id(
			Set<Planificacion> planificacionsForHora17Id) {
		this.planificacionsForHora17Id = planificacionsForHora17Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora24Id")
	public Set<Planificacion> getPlanificacionsForHora24Id() {
		return this.planificacionsForHora24Id;
	}

	public void setPlanificacionsForHora24Id(
			Set<Planificacion> planificacionsForHora24Id) {
		this.planificacionsForHora24Id = planificacionsForHora24Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora25Id")
	public Set<Planificacion> getPlanificacionsForHora25Id() {
		return this.planificacionsForHora25Id;
	}

	public void setPlanificacionsForHora25Id(
			Set<Planificacion> planificacionsForHora25Id) {
		this.planificacionsForHora25Id = planificacionsForHora25Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora26Id")
	public Set<Planificacion> getPlanificacionsForHora26Id() {
		return this.planificacionsForHora26Id;
	}

	public void setPlanificacionsForHora26Id(
			Set<Planificacion> planificacionsForHora26Id) {
		this.planificacionsForHora26Id = planificacionsForHora26Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora27Id")
	public Set<Planificacion> getPlanificacionsForHora27Id() {
		return this.planificacionsForHora27Id;
	}

	public void setPlanificacionsForHora27Id(
			Set<Planificacion> planificacionsForHora27Id) {
		this.planificacionsForHora27Id = planificacionsForHora27Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora1Id")
	public Set<Planificacion> getPlanificacionsForHora1Id() {
		return this.planificacionsForHora1Id;
	}

	public void setPlanificacionsForHora1Id(
			Set<Planificacion> planificacionsForHora1Id) {
		this.planificacionsForHora1Id = planificacionsForHora1Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora2Id")
	public Set<Planificacion> getPlanificacionsForHora2Id() {
		return this.planificacionsForHora2Id;
	}

	public void setPlanificacionsForHora2Id(
			Set<Planificacion> planificacionsForHora2Id) {
		this.planificacionsForHora2Id = planificacionsForHora2Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora20Id")
	public Set<Planificacion> getPlanificacionsForHora20Id() {
		return this.planificacionsForHora20Id;
	}

	public void setPlanificacionsForHora20Id(
			Set<Planificacion> planificacionsForHora20Id) {
		this.planificacionsForHora20Id = planificacionsForHora20Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora3Id")
	public Set<Planificacion> getPlanificacionsForHora3Id() {
		return this.planificacionsForHora3Id;
	}

	public void setPlanificacionsForHora3Id(
			Set<Planificacion> planificacionsForHora3Id) {
		this.planificacionsForHora3Id = planificacionsForHora3Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora21Id")
	public Set<Planificacion> getPlanificacionsForHora21Id() {
		return this.planificacionsForHora21Id;
	}

	public void setPlanificacionsForHora21Id(
			Set<Planificacion> planificacionsForHora21Id) {
		this.planificacionsForHora21Id = planificacionsForHora21Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora4Id")
	public Set<Planificacion> getPlanificacionsForHora4Id() {
		return this.planificacionsForHora4Id;
	}

	public void setPlanificacionsForHora4Id(
			Set<Planificacion> planificacionsForHora4Id) {
		this.planificacionsForHora4Id = planificacionsForHora4Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora22Id")
	public Set<Planificacion> getPlanificacionsForHora22Id() {
		return this.planificacionsForHora22Id;
	}

	public void setPlanificacionsForHora22Id(
			Set<Planificacion> planificacionsForHora22Id) {
		this.planificacionsForHora22Id = planificacionsForHora22Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora5Id")
	public Set<Planificacion> getPlanificacionsForHora5Id() {
		return this.planificacionsForHora5Id;
	}

	public void setPlanificacionsForHora5Id(
			Set<Planificacion> planificacionsForHora5Id) {
		this.planificacionsForHora5Id = planificacionsForHora5Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora23Id")
	public Set<Planificacion> getPlanificacionsForHora23Id() {
		return this.planificacionsForHora23Id;
	}

	public void setPlanificacionsForHora23Id(
			Set<Planificacion> planificacionsForHora23Id) {
		this.planificacionsForHora23Id = planificacionsForHora23Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora18Id")
	public Set<Planificacion> getPlanificacionsForHora18Id() {
		return this.planificacionsForHora18Id;
	}

	public void setPlanificacionsForHora18Id(
			Set<Planificacion> planificacionsForHora18Id) {
		this.planificacionsForHora18Id = planificacionsForHora18Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora19Id")
	public Set<Planificacion> getPlanificacionsForHora19Id() {
		return this.planificacionsForHora19Id;
	}

	public void setPlanificacionsForHora19Id(
			Set<Planificacion> planificacionsForHora19Id) {
		this.planificacionsForHora19Id = planificacionsForHora19Id;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<DetalleHorario> getDetalleHorarios() {
		return this.detalleHorarios;
	}

	public void setDetalleHorarios(Set<DetalleHorario> detalleHorarios) {
		this.detalleHorarios = detalleHorarios;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora7Id")
	public Set<Planificacion> getPlanificacionsForHora7Id() {
		return this.planificacionsForHora7Id;
	}

	public void setPlanificacionsForHora7Id(
			Set<Planificacion> planificacionsForHora7Id) {
		this.planificacionsForHora7Id = planificacionsForHora7Id;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horarioByHora6Id")
	public Set<Planificacion> getPlanificacionsForHora6Id() {
		return this.planificacionsForHora6Id;
	}

	public void setPlanificacionsForHora6Id(
			Set<Planificacion> planificacionsForHora6Id) {
		this.planificacionsForHora6Id = planificacionsForHora6Id;
	}
	
	@Column(name = "ESTADO", nullable = false)
	@NotNull	
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	@Column(name = "HORAS_TRABAJO")
	@NotNull	
	public Integer getHorasTrabajo() {
		return horasTrabajo;
	}

	public void setHorasTrabajo(Integer horasTrabajo) {
		this.horasTrabajo = horasTrabajo;
	}	
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<EmpleadoHorario> getEmpleadoHorarios() {
		return this.empleadoHorarios;
	}

	public void setEmpleadoHorarios(Set<EmpleadoHorario> empleadoHorarios) {
		this.empleadoHorarios = empleadoHorarios;
	}

	@Override
	public String toString() {
		return "horaId=" + horaId + ", descripcion=" + descripcion
				+ ", almuerzoMinutos=" + almuerzoMinutos + ", estado=" + estado
				+ ", codigo=" + codigo;
	}

}
