package com.casapazmino.fulltime.model;
// Generated 26/09/2011 09:54:50 AM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Max;
import org.hibernate.validator.Min;
import org.hibernate.validator.NotNull;

import com.casapazmino.fulltime.comun.Enumeraciones;

/**
 * HoraExtra generated by hbm2java
 */
@Entity
@Table(name = "hora_extra")
public class HoraExtra implements java.io.Serializable {

	private static final long serialVersionUID = -8942270537265806930L;
	
	private Integer horaExtraId;
	private String codigoDia;
	private Enumeraciones.diasSemana descripcion;
	private boolean diaLibre;
	private Date desde;
	private Date hasta;
	private Date desde1;
	private Date hasta1;
	private Date desde2;
	private Date hasta2;
	private Date desde3;
	private Date hasta3;
	private Date desde4;
	private Date hasta4;

	private BigDecimal porcentaje;
	private byte maximoDia;
	private byte maximoMes;

	private Set<AsistenciaHoraExtra> asistenciaHoraExtras = new HashSet<AsistenciaHoraExtra>(
			0);

	public HoraExtra() {
	}

	public HoraExtra(String codigoDia, Enumeraciones.diasSemana descripcion, boolean diaLibre, Date desde,
			Date hasta, Date desde1, Date hasta1, Date desde2, Date hasta2,
			Date desde3, Date hasta3, Date desde4, Date hasta4, BigDecimal porcentaje, byte maximoDia, byte maximoMes) {
		this.codigoDia = codigoDia;
		this.descripcion = descripcion;
		this.diaLibre = diaLibre;
		this.desde = desde;
		this.hasta = hasta;
		this.desde1 = desde1;
		this.hasta1 = hasta1;
		this.desde2 = desde2;
		this.hasta2 = hasta2;
		this.desde3 = desde3;
		this.hasta3 = hasta3;
		this.desde4 = desde4;
		this.hasta4 = hasta4;		
		this.porcentaje = porcentaje;
		this.maximoDia = maximoDia;
		this.maximoMes = maximoMes;
	}
	public HoraExtra(String codigoDia, Enumeraciones.diasSemana descripcion, boolean diaLibre, Date desde,
			Date hasta, Date desde1, Date hasta1, Date desde2, Date hasta2,
			Date desde3, Date hasta3, Date desde4, Date hasta4, BigDecimal porcentaje, byte maximoDia, byte maximoMes,
			Set<AsistenciaHoraExtra> asistenciaHoraExtras) {
		this.codigoDia = codigoDia;
		this.descripcion = descripcion;
		this.diaLibre = diaLibre;
		this.desde = desde;
		this.hasta = hasta;
		this.desde1 = desde1;
		this.hasta1 = hasta1;
		this.desde2 = desde2;
		this.hasta2 = hasta2;
		this.desde3 = desde3;
		this.hasta3 = hasta3;
		this.desde4 = desde4;
		this.hasta4 = hasta4;		
		this.porcentaje = porcentaje;
		this.maximoDia = maximoDia;
		this.maximoMes = maximoMes;
		this.asistenciaHoraExtras = asistenciaHoraExtras;
	}

	@Id
	@TableGenerator(name = "IDHORAEXTRA", table = "contadores", pkColumnName = "ID", pkColumnValue = "6", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDHORAEXTRA")
	@Column(name = "HORA_EXTRA_ID", unique = true, nullable = false)
	public Integer getHoraExtraId() {
		return this.horaExtraId;
	}

	public void setHoraExtraId(Integer horaExtraId) {
		this.horaExtraId = horaExtraId;
	}

	@Column(name = "CODIGO_DIA", nullable = false, length = 30)
	@NotNull
	public String getCodigoDia() {
		return codigoDia;
	}

	public void setCodigoDia(String codigoDia) {
		this.codigoDia = codigoDia;
	}
	
	@Column(name = "DESCRIPCION", nullable = false)
	@Enumerated(EnumType.ORDINAL)
	@NotNull
	public Enumeraciones.diasSemana getDescripcion(){
		return this.descripcion;
	}

	public void setDescripcion(Enumeraciones.diasSemana descripcion) {
		this.descripcion = descripcion;
	}

	
//	@NotNull
	@Column(name = "DIA_LIBRE", nullable = true)
	public boolean isDiaLibre() {
		return this.diaLibre;
	}

	public void setDiaLibre(boolean diaLibre) {
		this.diaLibre = diaLibre;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DESDE", nullable = false, length = 19)
	@NotNull
	public Date getDesde() {
		return this.desde;
	}

	public void setDesde(Date desde) {
		this.desde = desde;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HASTA", nullable = false, length = 19)
	@NotNull
	public Date getHasta() {
		return this.hasta;
	}

	public void setHasta(Date hasta) {
		this.hasta = hasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DESDE1", nullable = true, length = 19)
	public Date getDesde1() {
		return desde1;
	}

	public void setDesde1(Date desde1) {
		this.desde1 = desde1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HASTA1", nullable = true, length = 19)
	public Date getHasta1() {
		return hasta1;
	}

	public void setHasta1(Date hasta1) {
		this.hasta1 = hasta1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DESDE2", length = 19)
	public Date getDesde2() {
		return desde2;
	}

	public void setDesde2(Date desde2) {
		this.desde2 = desde2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HASTA2", length = 19)
	public Date getHasta2() {
		return hasta2;
	}

	public void setHasta2(Date hasta2) {
		this.hasta2 = hasta2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DESDE3", length = 19)
	public Date getDesde3() {
		return desde3;
	}

	public void setDesde3(Date desde3) {
		this.desde3 = desde3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HASTA3", length = 19)
	public Date getHasta3() {
		return hasta3;
	}

	public void setHasta3(Date hasta3) {
		this.hasta3 = hasta3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DESDE4", length = 19)
	public Date getDesde4() {
		return desde4;
	}

	public void setDesde4(Date desde4) {
		this.desde4 = desde4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HASTA4", length = 19)
	public Date getHasta4() {
		return hasta4;
	}

	public void setHasta4(Date hasta4) {
		this.hasta4 = hasta4;
	}

	@Column(name = "PORCENTAJE", nullable = true, precision = 4)
//	@NotNull
	@Min(0)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "MAXIMO_DIA", nullable = true)
//	@NotNull
	@Min(0)
	@Max(16)
	public byte getMaximoDia() {
		return this.maximoDia;
	}

	public void setMaximoDia(byte maximoDia) {
		this.maximoDia = maximoDia;
	}

	@Column(name = "MAXIMO_MES", nullable = true)
//	@NotNull
	@Min(0)
	public byte getMaximoMes() {
		return this.maximoMes;
	}

	public void setMaximoMes(byte maximoMes) {
		this.maximoMes = maximoMes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horaExtra")
	public Set<AsistenciaHoraExtra> getAsistenciaHoraExtras() {
		return this.asistenciaHoraExtras;
	}

	public void setAsistenciaHoraExtras(
			Set<AsistenciaHoraExtra> asistenciaHoraExtras) {
		this.asistenciaHoraExtras = asistenciaHoraExtras;
	}

//	@Override
//	public String toString() {
//		return "horaExtraId=" + horaExtraId + ", codigoDia="
//				+ codigoDia + ", descripcion=" + descripcion.toString() + ", desde=" + desde.toString() + ", hasta=" + hasta.toString()
//				+ ", desde1=" + desde1.toString() + ", hasta1=" + hasta1.toString() + ", desde2="
//				+ desde2.toString() + ", hasta2=" + hasta2.toString() + ", desde3=" + desde3.toString()
//				+ ", hasta3=" + hasta3.toString() + ", desde4=" + desde4.toString() + ", hasta4="
//				+ hasta4.toString() + ", porcentaje=" + porcentaje + ", maximoDia="
//				+ maximoDia + ", maximoMes=" + maximoMes;
//	}
	
	@Override
	public String toString() {
		return "horaExtraId=" + horaExtraId + ", codigoDia="
				+ codigoDia + ", descripcion=" + descripcion;
	}

	
}
