package com.casapazmino.fulltime.model;

// Generated 29-April-2014 11:48:41 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * TipoCargo generated by hbm2java
 */
@Entity
@Table(name = "permiso_autorizacion")
public class PermisoAutorizacion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long perm_aut_id;
	private Permiso permiso;
	private Empleado empleado;
	private Integer nivel;	
	private String estado;
	
	public PermisoAutorizacion() {

	}

	public PermisoAutorizacion(Permiso permiso, Empleado empleado, Integer nivel,String estado) {
		this.permiso=permiso;
		this.empleado=empleado;
		this.nivel=nivel;
		this.estado=estado;
	}

	@Id
	@TableGenerator(name = "IDPERMAUT", table = "contadores", pkColumnName = "ID", pkColumnValue = "47", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDPERMAUT")
	@Column(name = "PERM_AUT_ID", unique = true, nullable = false)
	public Long getPerm_aut_id() {
		return perm_aut_id;
	}

	public void setPerm_aut_id(Long perm_aut_id) {
		this.perm_aut_id = perm_aut_id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERM_ID", nullable = false)
	@NotNull
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "NIVEL", nullable = false)
	@NotNull
	public Integer getNivel(){
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "ESTADO", nullable = false)
	@NotNull
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}