package com.casapazmino.fulltime.model;
// Generated 30/10/2013 10:42:41 AM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * Planificacion generated by hbm2java
 */
@Entity
@Table(name = "planificacion")
public class Planificacion implements java.io.Serializable {

	private static final long serialVersionUID = 4001473278398007751L;
	
	private int id;
	private Empleado empleadoByEmplId;
	private Horario horarioByHora1Id;
	private Horario horarioByHora2Id;
	private Horario horarioByHora3Id;
	private Horario horarioByHora4Id;
	private Horario horarioByHora5Id;
	private Horario horarioByHora6Id;
	private Horario horarioByHora7Id;
	private Horario horarioByHora8Id;
	private Horario horarioByHora9Id;
	private Horario horarioByHora10Id;
	private Horario horarioByHora11Id;
	private Horario horarioByHora12Id;
	private Horario horarioByHora13Id;
	private Horario horarioByHora14Id;
	private Horario horarioByHora15Id;
	private Horario horarioByHora16Id;
	private Horario horarioByHora17Id;
	private Horario horarioByHora18Id;
	private Horario horarioByHora19Id;
	private Horario horarioByHora20Id;
	private Horario horarioByHora21Id;
	private Horario horarioByHora22Id;
	private Horario horarioByHora23Id;
	//private Empleado empleadoByEmpEmplId;
	private Horario horarioByHora24Id;
	private Horario horarioByHora25Id;
	private Horario horarioByHora26Id;
	private Horario horarioByHora27Id;
	private Horario horarioByHora28Id;
	private Horario horarioByHora29Id;
	private Horario horarioByHora30Id;
	private Horario horarioByHora31Id;
	private Integer anio;
	private Integer mes;
	private Integer estado;

	public Planificacion() {
	}

	public Planificacion(int id, Empleado empleadoByEmplId) {
		this.id = id;
		this.empleadoByEmplId = empleadoByEmplId;
	}
	public Planificacion(int id, Horario horarioByHora15Id,
			Horario horarioByHora9Id, Horario horarioByHora12Id,
			Horario horarioByHora21Id, Horario horarioByHora14Id,
			Horario horarioByHora23Id, Empleado empleadoByEmpEmplId,
			Horario horarioByHora13Id, Horario horarioByHora10Id,
			Horario horarioByHora18Id, Horario horarioByHora3Id,
			Horario horarioByHora31Id, Horario horarioByHora28Id,
			Horario horarioByHora25Id, Horario horarioByHora19Id,
			Horario horarioByHora22Id, Horario horarioByHora4Id,
			Horario horarioByHora27Id, Horario horarioByHora24Id,
			Horario horarioByHora5Id, Horario horarioByHora11Id,
			Horario horarioByHora6Id, Horario horarioByHora7Id,
			Horario horarioByHora17Id, Horario horarioByHora30Id,
			Horario horarioByHora26Id, Horario horarioByHora29Id,
			Horario horarioByHora1Id, Horario horarioByHora8Id,
			Horario horarioByHora20Id, Horario horarioByHora16Id,
			Empleado empleadoByEmplId, Horario horarioByHora2Id, Integer anio,
			Integer mes, Integer estado) {
		this.id = id;
		this.horarioByHora15Id = horarioByHora15Id;
		this.horarioByHora9Id = horarioByHora9Id;
		this.horarioByHora12Id = horarioByHora12Id;
		this.horarioByHora21Id = horarioByHora21Id;
		this.horarioByHora14Id = horarioByHora14Id;
		this.horarioByHora23Id = horarioByHora23Id;
		//this.empleadoByEmpEmplId = empleadoByEmpEmplId;
		this.horarioByHora13Id = horarioByHora13Id;
		this.horarioByHora10Id = horarioByHora10Id;
		this.horarioByHora18Id = horarioByHora18Id;
		this.horarioByHora3Id = horarioByHora3Id;
		this.horarioByHora31Id = horarioByHora31Id;
		this.horarioByHora28Id = horarioByHora28Id;
		this.horarioByHora25Id = horarioByHora25Id;
		this.horarioByHora19Id = horarioByHora19Id;
		this.horarioByHora22Id = horarioByHora22Id;
		this.horarioByHora4Id = horarioByHora4Id;
		this.horarioByHora27Id = horarioByHora27Id;
		this.horarioByHora24Id = horarioByHora24Id;
		this.horarioByHora5Id = horarioByHora5Id;
		this.horarioByHora11Id = horarioByHora11Id;
		this.horarioByHora6Id = horarioByHora6Id;
		this.horarioByHora7Id = horarioByHora7Id;
		this.horarioByHora17Id = horarioByHora17Id;
		this.horarioByHora30Id = horarioByHora30Id;
		this.horarioByHora26Id = horarioByHora26Id;
		this.horarioByHora29Id = horarioByHora29Id;
		this.horarioByHora1Id = horarioByHora1Id;
		this.horarioByHora8Id = horarioByHora8Id;
		this.horarioByHora20Id = horarioByHora20Id;
		this.horarioByHora16Id = horarioByHora16Id;
		this.empleadoByEmplId = empleadoByEmplId;
		this.horarioByHora2Id = horarioByHora2Id;
		this.anio = anio;
		this.mes = mes;
		this.estado = estado;
	}

	@Id
	@TableGenerator(name = "IDPLANIFICACION", table = "contadores", pkColumnName = "ID", pkColumnValue = "43", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDPLANIFICACION")
	@Column(name = "ID", unique = true, nullable = false)
	@NotNull
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA1_ID")
	public Horario getHorarioByHora1Id() {
		//if(horarioByHora1Id == null){
			//horarioByHora1Id = new Horario();
		//}
		return this.horarioByHora1Id;
	}

	public void setHorarioByHora1Id(Horario horarioByHora1Id) {
		this.horarioByHora1Id = horarioByHora1Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA2_ID")
	public Horario getHorarioByHora2Id() {
		//if(horarioByHora2Id == null){
			//horarioByHora2Id = new Horario();
		//}
		return this.horarioByHora2Id;
	}

	public void setHorarioByHora2Id(Horario horarioByHora2Id) {
		this.horarioByHora2Id = horarioByHora2Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA3_ID")
	public Horario getHorarioByHora3Id() {
		//if(horarioByHora3Id == null){
			//horarioByHora3Id = new Horario();
		//}
		return this.horarioByHora3Id;
	}

	public void setHorarioByHora3Id(Horario horarioByHora3Id) {
		this.horarioByHora3Id = horarioByHora3Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA4_ID")
	public Horario getHorarioByHora4Id() {
		//if(horarioByHora4Id == null){
			//horarioByHora4Id = new Horario();
		//}
		return this.horarioByHora4Id;
	}

	public void setHorarioByHora4Id(Horario horarioByHora4Id) {
		this.horarioByHora4Id = horarioByHora4Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA5_ID")
	public Horario getHorarioByHora5Id() {
		//if(horarioByHora5Id == null){
			//horarioByHora5Id = new Horario();
		//}
		return this.horarioByHora5Id;
	}

	public void setHorarioByHora5Id(Horario horarioByHora5Id) {
		this.horarioByHora5Id = horarioByHora5Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA6_ID")
	public Horario getHorarioByHora6Id() {
		//if(horarioByHora6Id == null){
			//horarioByHora6Id = new Horario();
		//}
		return this.horarioByHora6Id;
	}

	public void setHorarioByHora6Id(Horario horarioByHora6Id) {
		this.horarioByHora6Id = horarioByHora6Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA7_ID")
	public Horario getHorarioByHora7Id() {
		//if(horarioByHora7Id == null){
			//horarioByHora7Id = new Horario();
		//}
		return this.horarioByHora7Id;
	}

	public void setHorarioByHora7Id(Horario horarioByHora7Id) {
		this.horarioByHora7Id = horarioByHora7Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA8_ID")
	public Horario getHorarioByHora8Id() {
		//if(horarioByHora8Id == null){
			//horarioByHora8Id = new Horario();
		//}
		return this.horarioByHora8Id;
	}

	public void setHorarioByHora8Id(Horario horarioByHora8Id) {
		this.horarioByHora8Id = horarioByHora8Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA9_ID")
	public Horario getHorarioByHora9Id() {
		//if(horarioByHora9Id == null){
			//horarioByHora9Id = new Horario();
		//}
		return this.horarioByHora9Id;
	}

	public void setHorarioByHora9Id(Horario horarioByHora9Id) {
		this.horarioByHora9Id = horarioByHora9Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA10_ID")
	public Horario getHorarioByHora10Id() {
		//if(horarioByHora10Id == null){
			//horarioByHora10Id = new Horario();
		//}
		return this.horarioByHora10Id;
	}

	public void setHorarioByHora10Id(Horario horarioByHora10Id) {
		this.horarioByHora10Id = horarioByHora10Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA11_ID")
	public Horario getHorarioByHora11Id() {
	//	if(horarioByHora11Id == null){
			//horarioByHora11Id = new Horario();
		//}
		return this.horarioByHora11Id;
	}

	public void setHorarioByHora11Id(Horario horarioByHora11Id) {
		this.horarioByHora11Id = horarioByHora11Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA12_ID")
	public Horario getHorarioByHora12Id() {
		//if(horarioByHora12Id == null){
			//horarioByHora12Id = new Horario();
		//}
		return this.horarioByHora12Id;
	}

	public void setHorarioByHora12Id(Horario horarioByHora12Id) {
		this.horarioByHora12Id = horarioByHora12Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA13_ID")
	public Horario getHorarioByHora13Id() {
		//if(horarioByHora13Id == null){
			//horarioByHora13Id = new Horario();
		//}
		return this.horarioByHora13Id;
	}

	public void setHorarioByHora13Id(Horario horarioByHora13Id) {
		this.horarioByHora13Id = horarioByHora13Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA14_ID")
	public Horario getHorarioByHora14Id() {
		//if(horarioByHora14Id == null){
			//horarioByHora14Id = new Horario();
		//}
		return this.horarioByHora14Id;
	}

	public void setHorarioByHora14Id(Horario horarioByHora14Id) {
		this.horarioByHora14Id = horarioByHora14Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA15_ID")
	public Horario getHorarioByHora15Id() {
		//if(horarioByHora15Id == null){
			//horarioByHora15Id = new Horario();
		//}
		
		return this.horarioByHora15Id;
	}

	public void setHorarioByHora15Id(Horario horarioByHora15Id) {
		this.horarioByHora15Id = horarioByHora15Id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA16_ID")
	public Horario getHorarioByHora16Id() {
		//if(horarioByHora16Id == null){
			//horarioByHora16Id = new Horario();
		//}
		return this.horarioByHora16Id;
	}
	public void setHorarioByHora16Id(Horario horarioByHora16Id) {
		this.horarioByHora16Id = horarioByHora16Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA17_ID")
	public Horario getHorarioByHora17Id() {
		//if(horarioByHora17Id == null){
			//horarioByHora17Id = new Horario();
		//}
		return this.horarioByHora17Id;
	}

	public void setHorarioByHora17Id(Horario horarioByHora17Id) {
		this.horarioByHora17Id = horarioByHora17Id;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA18_ID")
	public Horario getHorarioByHora18Id() {
		//if(horarioByHora18Id == null){
			//horarioByHora18Id = new Horario();
		//}
		return this.horarioByHora18Id;
	}

	public void setHorarioByHora18Id(Horario horarioByHora18Id) {
		this.horarioByHora18Id = horarioByHora18Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA19_ID")
	public Horario getHorarioByHora19Id() {
		//if(horarioByHora19Id == null){
			//horarioByHora19Id = new Horario();
		//}
		return this.horarioByHora19Id;
	}

	public void setHorarioByHora19Id(Horario horarioByHora19Id) {
		this.horarioByHora19Id = horarioByHora19Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA20_ID")
	public Horario getHorarioByHora20Id() {
		//if(horarioByHora20Id == null){
			//horarioByHora20Id = new Horario();
		//}
		return this.horarioByHora20Id;
	}

	public void setHorarioByHora20Id(Horario horarioByHora20Id) {
		this.horarioByHora20Id = horarioByHora20Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA21_ID")
	public Horario getHorarioByHora21Id() {
		//if(horarioByHora21Id == null){
			//horarioByHora21Id = new Horario();
		//}
		return this.horarioByHora21Id;
	}

	public void setHorarioByHora21Id(Horario horarioByHora21Id) {
		this.horarioByHora21Id = horarioByHora21Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA22_ID")
	public Horario getHorarioByHora22Id() {
		//if(horarioByHora22Id == null){
			//horarioByHora22Id = new Horario();
		//}
		return this.horarioByHora22Id;
	}

	public void setHorarioByHora22Id(Horario horarioByHora22Id) {
		this.horarioByHora22Id = horarioByHora22Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA23_ID")
	public Horario getHorarioByHora23Id() {
		//if(horarioByHora23Id == null){
			//horarioByHora23Id = new Horario();
		//}
		return this.horarioByHora23Id;
	}

	public void setHorarioByHora23Id(Horario horarioByHora23Id) {
		this.horarioByHora23Id = horarioByHora23Id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA24_ID")
	public Horario getHorarioByHora24Id() {
		//if(horarioByHora24Id == null){
			//horarioByHora24Id = new Horario();
		//}
		return this.horarioByHora24Id;
	}

	public void setHorarioByHora24Id(Horario horarioByHora24Id) {
		this.horarioByHora24Id = horarioByHora24Id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA25_ID")
	public Horario getHorarioByHora25Id() {
		//if(horarioByHora25Id == null){
			//horarioByHora25Id = new Horario();
		//}
		return this.horarioByHora25Id;
	}

	public void setHorarioByHora25Id(Horario horarioByHora25Id) {
		this.horarioByHora25Id = horarioByHora25Id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA26_ID")
	public Horario getHorarioByHora26Id() {
		//if(horarioByHora26Id == null){
			//horarioByHora26Id = new Horario();
		//}
		return this.horarioByHora26Id;
	}

	public void setHorarioByHora26Id(Horario horarioByHora26Id) {
		this.horarioByHora26Id = horarioByHora26Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA27_ID")
	public Horario getHorarioByHora27Id() {
		//if(horarioByHora27Id == null){
			//horarioByHora27Id = new Horario();
		//}
		return this.horarioByHora27Id;
	}

	public void setHorarioByHora27Id(Horario horarioByHora27Id) {
		this.horarioByHora27Id = horarioByHora27Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA28_ID")
	public Horario getHorarioByHora28Id() {
		//if(horarioByHora28Id == null){
			//horarioByHora28Id = new Horario();
		//}
		return this.horarioByHora28Id;
	}

	public void setHorarioByHora28Id(Horario horarioByHora28Id) {
		this.horarioByHora28Id = horarioByHora28Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA29_ID")
	public Horario getHorarioByHora29Id() {
		//if(horarioByHora29Id == null){
			//horarioByHora29Id = new Horario();
		//}
		return this.horarioByHora29Id;
	}

	public void setHorarioByHora29Id(Horario horarioByHora29Id) {
		this.horarioByHora29Id = horarioByHora29Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA30_ID")
	public Horario getHorarioByHora30Id() {
		//if(horarioByHora30Id == null){
			//horarioByHora30Id = new Horario();
		//}
		return this.horarioByHora30Id;
	}

	public void setHorarioByHora30Id(Horario horarioByHora30Id) {
		this.horarioByHora30Id = horarioByHora30Id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA31_ID")
	public Horario getHorarioByHora31Id() {
		//if(horarioByHora31Id == null){
			//horarioByHora31Id = new Horario();
		//}
		return this.horarioByHora31Id;
	}

	public void setHorarioByHora31Id(Horario horarioByHora31Id) {
		this.horarioByHora31Id = horarioByHora31Id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleadoByEmplId() {
		if(empleadoByEmplId == null){
			empleadoByEmplId = new Empleado();
		}
		return this.empleadoByEmplId;
	}

	public void setEmpleadoByEmplId(Empleado empleadoByEmplId) {
		this.empleadoByEmplId = empleadoByEmplId;
	}
	

	@Column(name = "ANIO")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "MES")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "ESTADO")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

}
