package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia")
public class Provincia implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long provId;
	private Region region;
	private String codigo;
	private String descripcion;
	private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

	public Provincia() {
	}

	public Provincia(Region region, String codigo, String descripcion) {
		this.region = region;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Provincia(Region region, String codigo, String descripcion,
			Set<Ciudad> ciudads) {
		this.region = region;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.ciudads = ciudads;
	}

	@Id
	@TableGenerator(name = "IDPROVINCIA", table = "contadores", pkColumnName = "ID", pkColumnValue = "2", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDPROVINCIA")
	@Column(name = "PROV_ID", unique = true, nullable = false)
	public Long getProvId() {
		return this.provId;
	}

	public void setProvId(Long provId) {
		this.provId = provId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGI_ID", nullable = false)
	@NotNull
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "CODIGO", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<Ciudad> getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set<Ciudad> ciudads) {
		this.ciudads = ciudads;
	}

	@Override
	public String toString() {
		return "provId=" + provId 
				+ ", codigo=" + codigo + ", descripcion=" + descripcion;
	}

}
