package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * Reloj generated by hbm2java
 */
@Entity
@Table(name = "reloj")
public class Reloj implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long reloId;
	private String descripcion;
	private String ip;
	private String puertoCom;
	private String velocidadCom;
	private String marca;
	private String modelo;
	private String serie;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Reloj() {
	}

	public Reloj(String descripcion) {
		this.descripcion = descripcion;
	}
	public Reloj(String descripcion, String ip, String puertoCom,
			String velocidadCom, String marca, String modelo, String serie,
			Set<Empleado> empleados) {
		this.descripcion = descripcion;
		this.ip = ip;
		this.puertoCom = puertoCom;
		this.velocidadCom = velocidadCom;
		this.marca = marca;
		this.modelo = modelo;
		this.serie = serie;
		this.empleados = empleados;
	}

	@Id
	@TableGenerator(name = "IDRELOJ", table = "contadores", pkColumnName = "ID", pkColumnValue = "12", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDRELOJ")
	@Column(name = "RELO_ID", unique = true, nullable = false)
	public Long getReloId() {
		return this.reloId;
	}

	public void setReloId(Long reloId) {
		this.reloId = reloId;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "IP")
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "PUERTO_COM")
	public String getPuertoCom() {
		return this.puertoCom;
	}

	public void setPuertoCom(String puertoCom) {
		this.puertoCom = puertoCom;
	}

	@Column(name = "VELOCIDAD_COM")
	public String getVelocidadCom() {
		return this.velocidadCom;
	}

	public void setVelocidadCom(String velocidadCom) {
		this.velocidadCom = velocidadCom;
	}

	@Column(name = "MARCA")
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "MODELO")
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "SERIE")
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "reloj")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	@Override
	public String toString() {
		return "reloId=" + reloId + ", descripcion=" + descripcion
				+ ", ip=" + ip + ", puertoCom=" + puertoCom + ", velocidadCom="
				+ velocidadCom + ", marca=" + marca + ", modelo=" + modelo
				+ ", serie=" + serie;
	}

}
