package com.casapazmino.fulltime.model;

// Generated 29-April-2014 11:48:41 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * TipoCargo generated by hbm2java
 */
@Entity
@Table(name = "solicitud_vacacion_autoriza")
public class SolicitudVacacionAutorizacion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long sova_aut_id;
	private SolicitudVacacion solicitudVacacion;
	private Empleado empleado;
	private Integer nivel;	
	private String estado;
	
	public SolicitudVacacionAutorizacion() {

	}

	public SolicitudVacacionAutorizacion(SolicitudVacacion solicitudVacacion, Empleado empleado, Integer nivel,String estado) {
		this.solicitudVacacion=solicitudVacacion;
		this.empleado=empleado;
		this.nivel=nivel;
		this.estado=estado;
	}

	@Id
	@TableGenerator(name = "IDSOVAAUT", table = "contadores", pkColumnName = "ID", pkColumnValue = "48", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDSOVAAUT")
	@Column(name = "SOVA_AUT_ID", unique = true, nullable = false)
	public Long getSova_aut_id() {
		return sova_aut_id;
	}

	public void setSova_aut_id(Long sova_aut_id) {
		this.sova_aut_id = sova_aut_id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOVA", nullable = false)
	@NotNull
	public SolicitudVacacion getSolicitudVacacion() {
		return this.solicitudVacacion;
	}

	public void setSolicitudVacacion(SolicitudVacacion solicitudVacacion) {
		this.solicitudVacacion = solicitudVacacion;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "NIVEL", nullable = false)
	@NotNull
	public Integer getNivel(){
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "ESTADO", nullable = false)
	@NotNull
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}