package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * SolicitudVacacion generated by hbm2java
 */
@Entity
@Table(name = "solicitud_vacacion")
public class SolicitudVacacion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long sova;
	private Empleado empleadoByEmpEmplId;
	private DetalleTipoParametro detalleTipoParametro;
	private Horario horario;
	private Empleado empleadoByEmplId;
	private EmpleadoPeriodoVacacion empleadoPeriodoVacacion;
	private Date fechaDesde;
	private Date fechaHasta;
	private String telefono;
	private String direccion;
	private boolean correo;
	private Date fechaIngreso;
	private Date fechaUltVacacion;
	private Short diasPermiso;
	private Short diasPendientes;
	private Date liceFechaDesde;
	private Date liceFechaHasta;
	private Integer statusAccion;
	private Integer suspencion;
	private Date suspFechaDesde;
	private Date suspFechaHasta;
	
	private String estado;
	private Integer nivel;
	private Integer aprobacion;
	private Integer nivelRequerido;
	
	private Integer diasLaborables;
	private Integer diasLibres;
	
	private Set<SolicitudVacacionAutorizacion> solicitudVacacionAutorizacion = new HashSet<SolicitudVacacionAutorizacion>(0);

	public SolicitudVacacion() {
	}

	public SolicitudVacacion(DetalleTipoParametro detalleTipoParametro,
			Horario horario, Empleado empleadoByEmplId,
			EmpleadoPeriodoVacacion empleadoPeriodoVacacion, Date fechaDesde,
			Date fechaHasta, String estado, Integer nivel, Integer aprobacion, Integer nivelRequerido) {
		this.detalleTipoParametro = detalleTipoParametro;
		this.horario = horario;
		this.empleadoByEmplId = empleadoByEmplId;
		this.empleadoPeriodoVacacion = empleadoPeriodoVacacion;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.estado=estado;
		this.nivel=nivel;
		this.aprobacion=aprobacion;
		this.nivelRequerido=nivelRequerido;
	}
	public SolicitudVacacion(Empleado empleadoByEmpEmplId,
			DetalleTipoParametro detalleTipoParametro, Horario horario,
			Empleado empleadoByEmplId,
			EmpleadoPeriodoVacacion empleadoPeriodoVacacion, Date fechaDesde,
			Date fechaHasta, String telefono, String direccion, boolean correo,
			Date fechaIngreso, Date fechaUltVacacion, Short diasPermiso,
			Short diasPendientes, Date liceFechaDesde, Date liceFechaHasta,
			Integer statusAccion, Integer suspencion, Date suspFechaDesde,
			Date suspFechaHasta, String estado, Integer nivel, Integer aprobacion, Integer nivelRequerido) {
		this.empleadoByEmpEmplId = empleadoByEmpEmplId;
		this.detalleTipoParametro = detalleTipoParametro;
		this.horario = horario;
		this.empleadoByEmplId = empleadoByEmplId;
		this.empleadoPeriodoVacacion = empleadoPeriodoVacacion;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.telefono = telefono;
		this.direccion = direccion;
		this.correo = correo;
		this.fechaIngreso = fechaIngreso;
		this.fechaUltVacacion = fechaUltVacacion;
		this.diasPermiso = diasPermiso;
		this.diasPendientes = diasPendientes;
		this.liceFechaDesde = liceFechaDesde;
		this.liceFechaHasta = liceFechaHasta;
		this.statusAccion = statusAccion;
		this.suspencion = suspencion;
		this.suspFechaDesde = suspFechaDesde;
		this.suspFechaHasta = suspFechaHasta;
		this.estado=estado;
		this.nivel=nivel;
		this.aprobacion=aprobacion;
		this.nivelRequerido=nivelRequerido;
	}

	@Id
	@TableGenerator(name = "IDSOLVACACION", table = "contadores", pkColumnName = "ID", pkColumnValue = "31", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDSOLVACACION")
	@Column(name = "SOVA", unique = true, nullable = false)
	public Long getSova() {
		return this.sova;
	}

	public void setSova(Long sova) {
		this.sova = sova;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleadoByEmpEmplId() {
//		if (empleadoByEmpEmplId == null) {
//			empleadoByEmpEmplId = new Empleado();
//		}
		return this.empleadoByEmpEmplId;
	}

	public void setEmpleadoByEmpEmplId(Empleado empleadoByEmpEmplId) {
		this.empleadoByEmpEmplId = empleadoByEmpEmplId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTORIZADO", nullable = false)
	@NotNull
	public DetalleTipoParametro getDetalleTipoParametro() {
		return this.detalleTipoParametro;
	}

	public void setDetalleTipoParametro(
			DetalleTipoParametro detalleTipoParametro) {
		this.detalleTipoParametro = detalleTipoParametro;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORA_ID", nullable = false)
	@NotNull
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID", nullable = false)
	@NotNull
	public Empleado getEmpleadoByEmplId() {
		if (empleadoByEmplId == null){
			empleadoByEmplId = new Empleado();
		}
		return this.empleadoByEmplId;
	}

	public void setEmpleadoByEmplId(Empleado empleadoByEmplId) {
		this.empleadoByEmplId = empleadoByEmplId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPVA_ID", nullable = false)
	@NotNull
	public EmpleadoPeriodoVacacion getEmpleadoPeriodoVacacion() {
		return this.empleadoPeriodoVacacion;
	}

	public void setEmpleadoPeriodoVacacion(
			EmpleadoPeriodoVacacion empleadoPeriodoVacacion) {
		this.empleadoPeriodoVacacion = empleadoPeriodoVacacion;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_DESDE", nullable = false, length = 10)
	@NotNull
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_HASTA", nullable = false, length = 10)
	@NotNull
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Column(name = "TELEFONO")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "DIRECCION")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "CORREO", nullable = false)
	@NotNull
	public boolean isCorreo() {
		return this.correo;		
	}

	public void setCorreo(boolean correo) {
		this.correo = correo;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INGRESO", length = 10)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ULT_VACACION", length = 10)
	public Date getFechaUltVacacion() {
		return this.fechaUltVacacion;
	}

	public void setFechaUltVacacion(Date fechaUltVacacion) {
		this.fechaUltVacacion = fechaUltVacacion;
	}

	@Column(name = "DIAS_PERMISO")
	public Short getDiasPermiso() {
		return this.diasPermiso;
	}

	public void setDiasPermiso(Short diasPermiso) {
		this.diasPermiso = diasPermiso;
	}

	@Column(name = "DIAS_PENDIENTES")
	public Short getDiasPendientes() {
		return this.diasPendientes;
	}

	public void setDiasPendientes(Short diasPendientes) {
		this.diasPendientes = diasPendientes;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "LICE_FECHA_DESDE", length = 10)
	public Date getLiceFechaDesde() {
		return this.liceFechaDesde;
	}

	public void setLiceFechaDesde(Date liceFechaDesde) {
		this.liceFechaDesde = liceFechaDesde;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "LICE_FECHA_HASTA", length = 10)
	public Date getLiceFechaHasta() {
		return this.liceFechaHasta;
	}

	public void setLiceFechaHasta(Date liceFechaHasta) {
		this.liceFechaHasta = liceFechaHasta;
	}

	@Column(name = "STATUS_ACCION")
	public Integer getStatusAccion() {
		return this.statusAccion;
	}

	public void setStatusAccion(Integer statusAccion) {
		this.statusAccion = statusAccion;
	}

	@Column(name = "SUSPENCION")
	public Integer getSuspencion() {
		return this.suspencion;
	}

	public void setSuspencion(Integer suspencion) {
		this.suspencion = suspencion;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "SUSP_FECHA_DESDE", length = 10)
	public Date getSuspFechaDesde() {
		return this.suspFechaDesde;
	}

	public void setSuspFechaDesde(Date suspFechaDesde) {
		this.suspFechaDesde = suspFechaDesde;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "SUSP_FECHA_HASTA", length = 10)
	public Date getSuspFechaHasta() {
		return this.suspFechaHasta;
	}

	public void setSuspFechaHasta(Date suspFechaHasta) {
		this.suspFechaHasta = suspFechaHasta;
	}

	@Override
	public String toString() {
		return "sova=" + sova + ", empleadoByEmpEmplId="
				+ empleadoByEmpEmplId.getCodigoEmpleado() + ", detalleTipoParametro="
				+ detalleTipoParametro.getDescripcion() 
				+ ", empleadoByEmplId=" + empleadoByEmplId.getCodigoEmpleado()
				+ ", empleadoPeriodoVacacion=" + empleadoPeriodoVacacion.getEpvaId()
				+ ", fechaDesde=" + fechaDesde + ", fechaHasta=" + fechaHasta;
	}

	@Column(name = "ESTADO")
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "NIVEL", nullable = false)
	@NotNull
	public Integer getNivel() {
		return nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "APROBACION", nullable = false)
	@NotNull
	public Integer getAprobacion() {
		return aprobacion;
	}

	public void setAprobacion(Integer aprobacion) {
		this.aprobacion = aprobacion;
	}

	@Column(name = "NIVEL_REQUERIDO", nullable = true)
//	@NotNull
	public Integer getNivelRequerido() {
		return nivelRequerido;
	}

	public void setNivelRequerido(Integer nivelRequerido) {
		this.nivelRequerido = nivelRequerido;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudVacacion")
	public Set<SolicitudVacacionAutorizacion> getSolicitudVacacionAutorizacion() {
		return solicitudVacacionAutorizacion;
	}

	public void setSolicitudVacacionAutorizacion(Set<SolicitudVacacionAutorizacion> solicitudVacacionAutorizacion) {
		this.solicitudVacacionAutorizacion = solicitudVacacionAutorizacion;
	}

	@Column(name = "DIAS_LABORABLES", nullable = false)
	public Integer getDiasLaborables() {
		return diasLaborables;
	}

	public void setDiasLaborables(Integer diasLaborables) {
		this.diasLaborables = diasLaborables;
	}

	@Column(name = "DIAS_LIBRES", nullable = false)
	public Integer getDiasLibres() {
		return diasLibres;
	}

	public void setDiasLibres(Integer diasLibres) {
		this.diasLibres = diasLibres;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((sova == null) ? 0 : sova.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof SolicitudVacacion)) {
			return false;
		}
		SolicitudVacacion other = (SolicitudVacacion) obj;
		if (sova == null) {
			if (other.sova != null) {
				return false;
			}
		} else if (!sova.equals(other.sova)) {
			return false;
		}
		return true;
	}

}
