package com.casapazmino.fulltime.model;

// Generated 19/12/2011 08:09:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Timbre generated by hbm2java
 */
@Entity
@Table(name = "timbre")
public class Timbre implements java.io.Serializable {

	private static final long serialVersionUID = -7034644010047521890L;

	private int timbId;
	private Empleado empleado;
	private Date fechaHoraTimbre;
	private String codigoEmpleado;
	private String codigoReloj;
	private String accion;
	
	private Date fecha;
	private Date hora;
	
	private String teclaFuncion;
	private String observacion;

	public Timbre() {
	}

	public Timbre(int timbId, Date fechaHoraTimbre, String codigoEmpleado) {
		this.timbId = timbId;
		this.fechaHoraTimbre = fechaHoraTimbre;
		this.codigoEmpleado = codigoEmpleado;
	}

	public Timbre(int timbId, Date fechaHoraTimbre, String codigoEmpleado,
			String codigoReloj, String accion, Date fecha, Date hora, String teclaFuncion) {
		this.timbId = timbId;
		this.fechaHoraTimbre = fechaHoraTimbre;
		this.codigoEmpleado = codigoEmpleado;
		this.codigoReloj = codigoReloj;
		this.accion = accion;
		this.fecha = fecha;
		this.hora = hora;
		this.teclaFuncion = teclaFuncion;
	}

	@Id
	@TableGenerator(name = "IDTIMBRE", table = "contadores", pkColumnName = "ID", pkColumnValue = "32", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDTIMBRE")
	@Column(name = "TIMB_ID", unique = true, nullable = false)
	@NotNull
	public int getTimbId() {
		return this.timbId;
	}

	public void setTimbId(int timbId) {
		this.timbId = timbId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_HORA_TIMBRE", nullable = false, length = 19)
	@NotNull
	public Date getFechaHoraTimbre() {
		return this.fechaHoraTimbre;
	}

	public void setFechaHoraTimbre(Date fechaHoraTimbre) {
		this.fechaHoraTimbre = fechaHoraTimbre;
	}

	
	
	@Column(name = "CODIGO_EMPLEADO", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getCodigoEmpleado() {
		return this.codigoEmpleado;
	}

	public void setCodigoEmpleado(String codigoEmpleado) {
		this.codigoEmpleado = codigoEmpleado;
	}

	@Column(name = "CODIGO_RELOJ", length = 10)
	@Length(max = 10)
	public String getCodigoReloj() {
		return this.codigoReloj;
	}

	public void setCodigoReloj(String codigoReloj) {
		this.codigoReloj = codigoReloj;
	}

	@Column(name = "ACCION", length = 3)
	@Length(max = 3)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", length = 19)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HORA", length = 19)
	public Date getHora() {
		return hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "TECLA_FUNCION", length = 3)
	@Length(max = 3)
	@NotNull
	public String getTeclaFuncion() {
		return teclaFuncion;
	}

	public void setTeclaFuncion(String teclaFuncion) {
		this.teclaFuncion = teclaFuncion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_ID")	
	public Empleado getEmpleado() {
		return empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}
	
	@Column(name = "OBSERVACION")
	public String getObservacion() {
		return observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	

	@Override
	public String toString() {
		return "timbId=" + timbId + ", fechaHoraTimbre="
				+ fechaHoraTimbre + ", codigoEmpleado=" + codigoEmpleado
				+ ", codigoReloj=" + codigoReloj + ", accion=" + accion
				+ ", fecha=" + fecha + ", hora=" + hora + ", teclaFuncion="
				+ teclaFuncion;
	}

	
}
