package com.casapazmino.fulltime.model;
// Generated 10/01/2011 11:40:10 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * TipoParametro generated by hbm2java
 */
@Entity
@Table(name = "tipo_parametro")
public class TipoParametro implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long tipaId;
	private String descripcion;
	private Set<DetalleTipoParametro> detalleTipoParametros = new HashSet<DetalleTipoParametro>(
			0);

	public TipoParametro() {
	}

	public TipoParametro(String descripcion) {
		this.descripcion = descripcion;
	}

	public TipoParametro(String descripcion,
			Set<DetalleTipoParametro> detalleTipoParametros) {
		this.descripcion = descripcion;
		this.detalleTipoParametros = detalleTipoParametros;
	}

	@Id
	@Column(name = "TIPA_ID", nullable = false)
	public Long getTipaId() {
		return this.tipaId;
	}

	public void setTipaId(Long tipaId) {
		this.tipaId = tipaId;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoParametro")
	public Set<DetalleTipoParametro> getDetalleTipoParametros() {
		return this.detalleTipoParametros;
	}

	public void setDetalleTipoParametros(
			Set<DetalleTipoParametro> detalleTipoParametros) {
		this.detalleTipoParametros = detalleTipoParametros;
	}

	@Override
	public String toString() {
		return "tipaId=" + tipaId + ", descripcion="
				+ descripcion;
	}

}
