package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * TipoCargo generated by hbm2java
 */
@Entity
@Table(name = "tipo_cargo")
public class TipoCargo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long ticaId;
	private String descripcion;
	private Set<Cargo> cargos = new HashSet<Cargo>(0);

	public TipoCargo() {
	}

	public TipoCargo(String descripcion) {
		this.descripcion = descripcion;
	}

	public TipoCargo(String descripcion, Set<Cargo> cargos) {
		this.descripcion = descripcion;
		this.cargos = cargos;
	}

	@Id
	@TableGenerator(name = "IDTIPOCARGO", table = "contadores", pkColumnName = "ID", pkColumnValue = "14", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDTIPOCARGO")
	@Column(name = "TICA_ID", unique = true, nullable = false)
	public Long getTicaId() {
		return this.ticaId;
	}

	public void setTicaId(Long ticaId) {
		this.ticaId = ticaId;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCargo")
	public Set<Cargo> getCargos() {
		return this.cargos;
	}

	public void setCargos(Set<Cargo> cargos) {
		this.cargos = cargos;
	}

	@Override
	public String toString() {
		return "ticaId=" + ticaId + ", descripcion=" + descripcion;
	}

}