package com.casapazmino.fulltime.model;

// Generated 12-Jan-2011 12:14:41 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * Titulo generated by hbm2java
 */
@Entity
@Table(name = "titulo")
public class Titulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long tituId;
	private String descripcion;
	private Set<EmpleadoTitulo> empleadoTitulos = new HashSet<EmpleadoTitulo>(0);

	public Titulo() {
	}

	public Titulo(String descripcion) {
		this.descripcion = descripcion;
	}

	public Titulo(String descripcion, Set<EmpleadoTitulo> empleadoTitulos) {
		this.descripcion = descripcion;
		this.empleadoTitulos = empleadoTitulos;
	}

	@Id
	@TableGenerator(name = "IDTITULO", table = "contadores", pkColumnName = "ID", pkColumnValue = "8", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDTITULO")
	@Column(name = "TITU_ID", unique = true, nullable = false)
	public Long getTituId() {
		return this.tituId;
	}

	public void setTituId(Long tituId) {
		this.tituId = tituId;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titulo")
	public Set<EmpleadoTitulo> getEmpleadoTitulos() {
		return this.empleadoTitulos;
	}

	public void setEmpleadoTitulos(Set<EmpleadoTitulo> empleadoTitulos) {
		this.empleadoTitulos = empleadoTitulos;
	}

	@Override
	public String toString() {
		return "tituId=" + tituId + ", descripcion=" + descripcion;
	}

}
