package com.casapazmino.fulltime.seguridad.model;
// Generated 10/01/2011 11:40:10 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Grupos generated by hbm2java
 */
@Entity
@Table(name = "grupos")
public class Grupos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String nombre;
	private String descripcion;
	private Boolean expandible;
	private Integer orden;
	private String etiqueta;
	private Set<ItemMenu> itemMenus = new HashSet<ItemMenu>(0);
	private Set<Subgrupos> subgruposes = new HashSet<Subgrupos>(0);
	private Set<ItemsMenuRoles> itemsMenuRoleses = new HashSet<ItemsMenuRoles>(
			0);

	public Grupos() {
	}

	public Grupos(String nombre, String descripcion, Boolean expandible,
			Integer orden, String etiqueta, Set<ItemMenu> itemMenus,
			Set<Subgrupos> subgruposes, Set<ItemsMenuRoles> itemsMenuRoleses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.expandible = expandible;
		this.orden = orden;
		this.etiqueta = etiqueta;
		this.itemMenus = itemMenus;
		this.subgruposes = subgruposes;
		this.itemsMenuRoleses = itemsMenuRoleses;
	}

	@Id
	@TableGenerator(name = "IDGRUPOS", table = "contadores", pkColumnName = "ID", pkColumnValue = "37", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDGRUPOS")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

//	@Pattern(regex=".*[a-zA-Z&&[^\\s]].*", message="No se permite espacios")
	
	@Column(name = "nombre", length = 50, nullable = false)
	@Length(max = 50)
	@NotNull
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100, nullable = false)
	@Length(max = 100)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "expandible")
	public Boolean getExpandible() {
		return this.expandible;
	}

	public void setExpandible(Boolean expandible) {
		this.expandible = expandible;
	}

	@Column(name = "orden", nullable = false)
	@NotNull
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "etiqueta", length = 30, nullable = false)
	@Length(max = 30)
	@NotNull
	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupos")
	public Set<ItemMenu> getItemMenus() {
		return this.itemMenus;
	}

	public void setItemMenus(Set<ItemMenu> itemMenus) {
		this.itemMenus = itemMenus;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupos")
	public Set<Subgrupos> getSubgruposes() {
		return this.subgruposes;
	}

	public void setSubgruposes(Set<Subgrupos> subgruposes) {
		this.subgruposes = subgruposes;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupos")
	public Set<ItemsMenuRoles> getItemsMenuRoleses() {
		return this.itemsMenuRoleses;
	}

	public void setItemsMenuRoleses(Set<ItemsMenuRoles> itemsMenuRoleses) {
		this.itemsMenuRoleses = itemsMenuRoleses;
	}

	@Override
	public String toString() {
		return "id=" + id + ", nombre=" + nombre + ", descripcion="
				+ descripcion + ", expandible=" + expandible + ", orden="
				+ orden + ", etiqueta=" + etiqueta;
	}

}
