package com.casapazmino.fulltime.seguridad.model;
// Generated 10/01/2011 11:40:10 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * PermisosMenu generated by hbm2java
 */
@Entity
@Table(name = "permisos_menu")
public class PermisosMenu implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Roles roles;
	private Boolean crear;
	private Boolean modificar;
	private Boolean eliminar;
	private Boolean ver;
	private Boolean imprimir;
	private Boolean permisos;
	private Boolean vacaciones;
	private Boolean global;
	private Boolean eliminarPerm;
	private Boolean autorizarPerm;
	private Boolean legalizarPerm;
	private Boolean modificar_planificacion;	
	private int accesoEmpleados;
	
	private Boolean actualizarPendiente;
	private Boolean actualizarAutorizado;
	private Boolean eliminarPendiente;
	private Boolean eliminarAutorizado;	
	private Boolean autorizarVacacion;

	public PermisosMenu() {
	}

	public PermisosMenu(Roles roles) {
		this.roles = roles;
	}
	
	public PermisosMenu(Roles roles, Boolean crear, Boolean modificar,
			Boolean eliminar, Boolean ver, Boolean imprimir, Boolean permisos,
			Boolean vacaciones, Boolean global, Boolean legalizarPerm, int accesoEmpleados, boolean modificar_planificacion) {
		this.roles = roles;
		this.crear = crear;
		this.modificar = modificar;
		this.eliminar = eliminar;
		this.ver = ver;
		this.imprimir = imprimir;
		this.permisos = permisos;
		this.vacaciones = vacaciones;
		this.global = global;
		this.legalizarPerm = legalizarPerm;
		this.accesoEmpleados =  accesoEmpleados;
		this.modificar_planificacion=modificar_planificacion;		
	}

	@Id
	@TableGenerator(name = "IDPERMISOSMENU", table = "contadores", pkColumnName = "ID", pkColumnValue = "41", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDPERMISOSMENU")
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLES", nullable = false)
	@NotNull
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "CREAR")
	public Boolean getCrear() {
		return this.crear;
	}

	public void setCrear(Boolean crear) {
		this.crear = crear;
	}

	@Column(name = "MODIFICAR")
	public Boolean getModificar() {
		return this.modificar;
	}

	public void setModificar(Boolean modificar) {
		this.modificar = modificar;
	}

	@Column(name = "ELIMINAR")
	public Boolean getEliminar() {
		return this.eliminar;
	}

	public void setEliminar(Boolean eliminar) {
		this.eliminar = eliminar;
	}

	@Column(name = "VER")
	public Boolean getVer() {
		return this.ver;
	}

	public void setVer(Boolean ver) {
		this.ver = ver;
	}

	@Column(name = "IMPRIMIR")
	public Boolean getImprimir() {
		return this.imprimir;
	}

	public void setImprimir(Boolean imprimir) {
		this.imprimir = imprimir;
	}

	@Column(name = "PERMISOS")
	public Boolean getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Boolean permisos) {
		this.permisos = permisos;
	}

	@Column(name = "VACACIONES")
	public Boolean getVacaciones() {
		return this.vacaciones;
	}

	public void setVacaciones(Boolean vacaciones) {
		this.vacaciones = vacaciones;
	}

	@Column(name = "GLOBAL")
	public Boolean getGlobal() {
		return this.global;
	}

	public void setGlobal(Boolean global) {
		this.global = global;
	}

	@Column(name = "ELIMINAR_PERM")
	public Boolean getEliminarPerm() {
		return eliminarPerm;
	}

	public void setEliminarPerm(Boolean eliminarPerm) {
		this.eliminarPerm = eliminarPerm;
	}

	@Column(name = "AUTORIZAR_PERM")
	public Boolean getAutorizarPerm() {
		return autorizarPerm;
	}

	public void setAutorizarPerm(Boolean autorizarPerm) {
		this.autorizarPerm = autorizarPerm;
	}

	@Column(name = "LEGALIZAR_PERM")
	public Boolean getLegalizarPerm() {
		return legalizarPerm;
	}

	public void setLegalizarPerm(Boolean legalizarPerm) {
		this.legalizarPerm = legalizarPerm;
	}

	@Column(name = "ACCESO_EMPLEADOS")
	public int getAccesoEmpleados() {
		return accesoEmpleados;
	}

	public void setAccesoEmpleados(int accesoEmpleados) {
		this.accesoEmpleados = accesoEmpleados;
	}

	@Column(name = "MODIFICAR_PLANIFICACION")
	public Boolean getModificar_planificacion() {
		return modificar_planificacion;
	}

	public void setModificar_planificacion(Boolean modificar_planificacion) {
		this.modificar_planificacion = modificar_planificacion;
	}

	@Override
	public String toString() {
		return "id=" + id + ", crear="
				+ crear + ", modificar=" + modificar + ", eliminar=" + eliminar
				+ ", ver=" + ver + ", imprimir=" + imprimir + ", permisos="
				+ permisos + ", vacaciones=" + vacaciones + ", global="
				+ global + ", eliminarPerm=" + eliminarPerm
				+ ", autorizarPerm=" + autorizarPerm + ", legalizarPerm="
				+ legalizarPerm + ", modificar_planificacion="
				+ modificar_planificacion + ", accesoEmpleados="
				+ accesoEmpleados;
	}

	@Column(name = "ACTUALIZAR_PENDIENTE")
	public Boolean getActualizarPendiente() {
		return actualizarPendiente;
	}

	public void setActualizarPendiente(Boolean actualizarPendiente) {
		this.actualizarPendiente = actualizarPendiente;
	}

	@Column(name = "ACTUALIZAR_AUTORIZADO")
	public Boolean getActualizarAutorizado() {
		return actualizarAutorizado;
	}

	public void setActualizarAutorizado(Boolean actualizarAutorizado) {
		this.actualizarAutorizado = actualizarAutorizado;
	}

	@Column(name = "ELIMINAR_PENDIENTE")
	public Boolean getEliminarPendiente() {
		return eliminarPendiente;
	}

	public void setEliminarPendiente(Boolean eliminarPendiente) {
		this.eliminarPendiente = eliminarPendiente;
	}

	@Column(name = "ELIMINAR_AUTORIZADO")
	public Boolean getEliminarAutorizado() {
		return eliminarAutorizado;
	}

	public void setEliminarAutorizado(Boolean eliminarAutorizado) {
		this.eliminarAutorizado = eliminarAutorizado;
	}

	@Column(name = "AUTORIZAR_VACACION")
	public Boolean getAutorizarVacacion() {
		return autorizarVacacion;
	}

	public void setAutorizarVacacion(Boolean autorizarVacacion) {
		this.autorizarVacacion = autorizarVacacion;
	}
}
