package com.casapazmino.fulltime.seguridad.model;
// Generated 10/01/2011 11:40:10 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.validator.NotNull;

/**
 * UsuariosRoles generated by hbm2java
 */
@Entity
@Table(name = "usuarios_roles")
public class UsuariosRoles implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Roles roles;
	private Usuarios usuarios;

	public UsuariosRoles() {
		this.roles=new Roles();
		this.usuarios=new Usuarios();
	}

	public UsuariosRoles(Roles roles, Usuarios usuarios) {
		this.roles = roles;
		this.usuarios = usuarios;
	}

	@Id
	@TableGenerator(name = "IDUSERROLES", table = "contadores", pkColumnName = "ID", pkColumnValue = "34", valueColumnName = "CONTADOR", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "IDUSERROLES")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roles", nullable = false)
	@NotNull
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarios", nullable = false)
	@NotNull
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Override
	public String toString() {
		return "id=" + id + ", roles=" + roles.getDescripcion() + ", usuarios="
				+ usuarios.getUsuario();
	}

}
